INSERT INTO public.exercises (name, category, target_muscle) VALUES
('Sentadilla (Squat)', 'Pierna', 'Cuádriceps'),
('Prensa de piernas', 'Pierna', 'Cuádriceps'),
('Extensión de piernas', 'Pierna', 'Cuádriceps'),
('Peso muerto (Deadlift)', 'Pierna', 'Isquiotibiales'),
('Curl de pierna sentado', 'Pierna', 'Isquiotibiales'),
('Elevación de talones (Calf raise)', 'Pierna', 'Pantorrillas'),
('Press de banca plano', 'Pecho', 'Pectoral mayor'),
('Press de banca inclinado', 'Pecho', 'Pectoral mayor'),
('Aperturas con mancuernas', 'Pecho', 'Pectoral mayor'),
('Flexiones de pecho', 'Pecho', 'Pectoral mayor'),
('Dominadas (Pull-ups)', 'Espalda', 'Dorsales'),
('Jalón al pecho', 'Espalda', 'Dorsales'),
('Remo con barra', 'Espalda', 'Dorsales'),
('Remo en polea baja', 'Espalda', 'Dorsales'),
('Press militar (hombro)', 'Hombro', 'Deltoides'),
('Elevaciones laterales', 'Hombro', 'Deltoides'),
('Pájaro (Elevación posterior)', 'Hombro', 'Deltoides'),
('Curl de bíceps con barra', 'Brazos', 'Bíceps'),
('Curl de bíceps con mancuernas', 'Brazos', 'Bíceps'),
('Press francés', 'Brazos', 'Tríceps'),
('Extensión de tríceps en polea', 'Brazos', 'Tríceps'),
('Plancha abdominal', 'Core', 'Abdominales'),
('Crunch abdominal', 'Core', 'Abdominales'),
('Elevación de piernas', 'Core', 'Abdominales');
