// Mapa de traducciones de ejercicios al español (generado desde exercises-dataset).
// Traducciones curadas por algoritmo con reordenamiento natural.
export const EXERCISE_NAMES_ES: Record<string, string> = {
  "3/4 sit-up": "Abdominal 3/4",
  "45° side bend": "",
  "air bike": "Bicicleta en el aire",
  "all fours squad stretch": "Estiramiento de sentadilla en cuatro apoyos",
  "alternate heel touchers": "Toques de talones alternos",
  "alternate lateral pulldown": "Jalón lateral alterno",
  "ankle circles": "Círculos de tobillo",
  "archer pull up": "Dominada arquera",
  "archer push up": "Flexión arquera",
  "arm slingers hanging bent knee legs": "",
  "arm slingers hanging straight legs": "",
  "arms apart circular toe touch (male)": "Toque de puntas circular con brazos separados",
  "arms overhead full sit-up (male)": "Abdominal completo con brazos arriba",
  "assisted chest dip (kneeling)": "Fondo de pecho de rodillas",
  "assisted hanging knee raise": "Elevación de rodillas colgado",
  "assisted hanging knee raise with throw down": "Elevación de rodillas colgado con descenso",
  "assisted lying calves stretch": "Estiramiento de pantorrillas acostado",
  "assisted lying glutes stretch": "Estiramiento de glúteos acostado",
  "assisted lying gluteus and piriformis stretch": "Estiramiento de piriforme asistido acostado gluteus",
  "assisted lying leg raise with lateral throw down": "Elevación de piernas acostado con descenso lateral",
  "assisted lying leg raise with throw down": "Elevación de piernas acostado con descenso",
  "assisted motion russian twist": "Giro ruso asistido",
  "assisted parallel close grip pull-up": "Dominada agarre cerrado paralelo",
  "assisted prone hamstring": "Isquiotibial boca abajo",
  "assisted prone lying quads stretch": "Estiramiento de cuádriceps boca abajo",
  "assisted prone rectus femoris stretch": "Estiramiento de recto femoral asistido boca abajo",
  "assisted pull-up": "Dominada asistida",
  "assisted seated pectoralis major stretch with stability ball": "Estiramiento de pectoral mayor sentado con balón suizo",
  "assisted side lying adductor stretch": "Estiramiento de aductores acostado de lado",
  "assisted sit-up": "Abdominal asistido",
  "assisted standing chin-up": "Dominada supina de pie",
  "assisted standing pull-up": "Dominada de pie",
  "assisted standing triceps extension (with towel)": "Extensión de tríceps de pie (con toalla)",
  "assisted triceps dip (kneeling)": "Fondo de tríceps de rodillas",
  "assisted wide-grip chest dip (kneeling)": "Fondo de pecho agarre amplio de rodillas",
  "astride jumps (male)": "Saltos con piernas abiertas",
  "back and forth step": "Paso adelante y atrás",
  "back extension on exercise ball": "Extensión de espalda sobre balón suizo",
  "back lever": "Palanca de espalda",
  "back pec stretch": "Estiramiento de pecho y espalda",
  "backward jump": "Salto hacia atrás",
  "balance board": "Tabla de equilibrio",
  "band alternating biceps curl": "Curl de bíceps alterno con banda",
  "band alternating v-up": " con banda elástica",
  "band assisted pull-up": "Dominada asistida con banda",
  "band assisted wheel rollerout": "Rodamiento con rueda asistido con banda",
  "band bench press": "Press de banca con banda",
  "band bent-over hip extension": "Extensión de cadera inclinado con banda",
  "band bicycle crunch": "Crunch de bicicleta con banda",
  "band close-grip pulldown": "Jalón agarre cerrado con banda",
  "band close-grip push-up": "Flexión agarre cerrado con banda",
  "band concentration curl": "Curl concentrado con banda",
  "band fixed back close grip pulldown": "Jalón agarre cerrado con banda",
  "band fixed back underhand pulldown": "Jalón agarre supino con banda",
  "band front lateral raise": "Elevación lateral frontal con banda",
  "band front raise": "Elevación frontal con banda",
  "band hip lift": "Elevación de cadera con banda",
  "band horizontal pallof press": "Press pallof horizontal con banda",
  "band jack knife sit-up": "Abdominal navaja con banda",
  "band kneeling one arm pulldown": "Jalón a un brazo de rodillas con banda",
  "band kneeling twisting crunch": "Crunch con giro de rodillas con banda",
  "band lying hip internal rotation": "Rotación interna de cadera acostado con banda",
  "band lying straight leg raise": "Elevación de pierna recta acostado con banda",
  "band one arm overhead biceps curl": "Curl de bíceps a un brazo con banda",
  "band one arm single leg split squat": "Sentadilla búlgara a una pierna con banda",
  "band one arm standing low row": "Remo bajo a un brazo de pie con banda",
  "band one arm twisting chest press": "Press de pecho con giro a un brazo con banda",
  "band one arm twisting seated row": "Remo sentado con giro a un brazo con banda",
  "band pull through": "Jalón entre piernas con banda",
  "band push sit-up": "Abdominal con empuje con banda",
  "band reverse fly": "Apertura posterior con banda",
  "band reverse wrist curl": "Curl de muñeca invertido con banda",
  "band seated hip internal rotation": "Rotación interna de cadera sentado con banda",
  "band seated twist": "Giro sentado con banda",
  "band shoulder press": "Press de hombros con banda",
  "band shrug": "Encogimiento con banda",
  "band side triceps extension": "Extensión de tríceps lateral con banda",
  "band single leg calf raise": "Elevación de pantorrillas a una pierna con banda",
  "band single leg reverse calf raise": "Elevación de pantorrillas invertido a una pierna con banda",
  "band single leg split squat": "Sentadilla búlgara a una pierna con banda",
  "band squat": "Sentadilla con banda",
  "band squat row": "Sentadilla remo con banda elástica",
  "band standing crunch": "Crunch de pie con banda",
  "band standing rear delt row": "Remo de pie rear delt con banda elástica",
  "band standing twisting crunch": "Crunch de pie con giro con banda elástica",
  "band step-up": "Subida a cajón con banda elástica",
  "band stiff leg deadlift": "Peso muerto piernas rígidas con banda",
  "band straight back stiff leg deadlift": "Peso muerto piernas rígidas con banda",
  "band straight leg deadlift": "Peso muerto piernas rectas con banda",
  "band twisting overhead press": "Press con giro sobre la cabeza con banda elástica",
  "band two legs calf raise - (band under both legs) v. 2": "Elevación de pantorrillas two piernas - v. 2 con banda elástica (Band under both piernas)",
  "band underhand pulldown": "Jalón agarre supino con banda elástica",
  "band v-up": " con banda elástica",
  "band vertical pallof press": "Press vertical pallof con banda elástica",
  "band wrist curl": "Curl de muñeca con banda elástica",
  "band y-raise": " con banda elástica",
  "barbell alternate biceps curl": "Curl de bíceps alterno con barra",
  "barbell bench front squat": "Sentadilla bench frontal con barra",
  "barbell bench press": "Press de banca con barra",
  "barbell bench squat": "Sentadilla bench con barra",
  "barbell bent arm pullover": "Pullover con brazos flexionados con barra",
  "barbell bent over row": "Remo con barra",
  "barbell biceps curl (with arm blaster)": "Curl de bíceps con barra (Brazo blaster)",
  "barbell clean and press": "Press cargada con barra",
  "barbell clean-grip front squat": "Sentadilla clean-grip frontal con barra",
  "barbell close-grip bench press": "Press de banca agarre cerrado",
  "barbell curl": "Curl con barra",
  "barbell deadlift": "Peso muerto con barra",
  "barbell decline bench press": "Press de banca declinado con barra",
  "barbell decline bent arm pullover": " con barra",
  "barbell decline close grip to skull press": "Press declinado agarre cerrado skull con barra",
  "barbell decline pullover": " con barra",
  "barbell decline wide-grip press": "Press declinado agarre amplio con barra",
  "barbell decline wide-grip pullover": " con barra",
  "barbell drag curl": "Curl drag con barra",
  "barbell floor calf raise": "Elevación de pantorrillas floor con barra",
  "barbell front chest squat": "Sentadilla frontal pecho con barra",
  "barbell front raise": "Elevación frontal con barra",
  "barbell front raise and pullover": "Elevación frontal pullover con barra",
  "barbell front squat": "Sentadilla frontal con barra",
  "barbell full squat": "Sentadilla completa con barra",
  "barbell full squat (back pov)": "Sentadilla completa con barra",
  "barbell full squat (side pov)": "Sentadilla completa con barra",
  "barbell full zercher squat": "Sentadilla completa zercher con barra",
  "barbell glute bridge": "Puente de glúteos con barra",
  "barbell glute bridge two legs on bench (male)": "Puente de glúteos two piernas bench con barra (Male)",
  "barbell good morning": " con barra",
  "barbell guillotine bench press": "Press de banca guillotine con barra",
  "barbell hack squat": "Sentadilla hack con barra",
  "barbell high bar squat": "Sentadilla alta bar con barra",
  "barbell incline bench press": "Press de banca inclinado con barra",
  "barbell incline close grip bench press": "Press de banca inclinado agarre cerrado con barra",
  "barbell incline reverse-grip press": "Press inclinado agarre inverso con barra",
  "barbell incline row": "Remo inclinado con barra",
  "barbell incline shoulder raise": "Elevación de hombros inclinado con barra",
  "barbell jefferson squat": "Sentadilla jefferson con barra",
  "barbell jm bench press": "Press de banca jm con barra",
  "barbell jump squat": "Sentadilla jump con barra",
  "barbell lateral lunge": "Zancada lateral con barra",
  "barbell low bar squat": "Sentadilla bajo bar con barra",
  "barbell lunge": "Zancada con barra",
  "barbell lying back of the head tricep extension": "Extensión de tríceps acostado espalda head con barra",
  "barbell lying close-grip press": "Press acostado agarre cerrado con barra",
  "barbell lying close-grip triceps extension": "Extensión de tríceps acostado agarre cerrado con barra",
  "barbell lying extension": "Extensión acostado con barra",
  "barbell lying lifting (on hip)": " con barra (Cadera)",
  "barbell lying preacher curl": "Curl acostado preacher con barra",
  "barbell lying triceps extension": "Extensión de tríceps acostado con barra",
  "barbell lying triceps extension skull crusher": "Extensión de tríceps acostado skull crusher con barra",
  "barbell narrow stance squat": "Sentadilla narrow stance con barra",
  "barbell one arm bent over row": "Remo inclinado un brazo con barra",
  "barbell one arm floor press": "Press un brazo floor con barra",
  "barbell one arm side deadlift": "Peso muerto un brazo lateral con barra",
  "barbell one arm snatch": "Arranque un brazo con barra",
  "barbell one leg squat": "Sentadilla una pierna con barra",
  "barbell overhead squat": "Sentadilla sobre la cabeza con barra",
  "barbell palms down wrist curl over a bench": "Curl de muñeca palms down over bench con barra",
  "barbell palms up wrist curl over a bench": "Curl de muñeca palms up over bench con barra",
  "barbell pendlay row": "Remo pendlay con barra",
  "barbell pin presses": " con barra",
  "barbell preacher curl": "Curl predicador con barra",
  "barbell press sit-up": "Abdominal press con barra",
  "barbell prone incline curl": "Curl boca abajo inclinado con barra",
  "barbell pullover": " con barra",
  "barbell pullover to press": "Press pullover con barra",
  "barbell rack pull": "Jalón rack con barra",
  "barbell rear delt raise": "Elevación rear delt con barra",
  "barbell rear delt row": "Remo rear delt con barra",
  "barbell rear lunge": "Zancada hacia atrás con barra",
  "barbell rear lunge v. 2": "Zancada rear v. 2 con barra",
  "barbell revers wrist curl v. 2": "Curl de muñeca revers v. 2 con barra",
  "barbell reverse close-grip bench press": "Press de banca invertido agarre cerrado con barra",
  "barbell reverse curl": "Curl invertido con barra",
  "barbell reverse grip bent over row": "Remo inclinado agarre inverso con barra",
  "barbell reverse grip decline bench press": "Press de banca agarre inverso declinado con barra",
  "barbell reverse grip incline bench press": "Press de banca agarre inverso inclinado con barra",
  "barbell reverse grip incline bench row": "Remo agarre inverso inclinado bench con barra",
  "barbell reverse grip skullcrusher": " con barra",
  "barbell reverse preacher curl": "Curl invertido preacher con barra",
  "barbell reverse wrist curl": "Curl de muñeca invertido con barra",
  "barbell rollerout": " con barra",
  "barbell rollerout from bench": " con barra",
  "barbell romanian deadlift": "Peso muerto romanian con barra",
  "barbell seated behind head military press": "Press sentado por detrás head military con barra",
  "barbell seated bradford rocky press": "Press sentado bradford rocky con barra",
  "barbell seated calf raise": "Elevación de pantorrillas sentado con barra",
  "barbell seated close grip behind neck triceps extension": "Extensión de tríceps sentado agarre cerrado por detrás cuello con barra",
  "barbell seated close-grip concentration curl": "Curl sentado agarre cerrado concentration con barra",
  "barbell seated good morning": " con barra",
  "barbell seated overhead press": "Press sentado sobre la cabeza con barra",
  "barbell seated overhead triceps extension": "Extensión de tríceps sentado sobre la cabeza con barra",
  "barbell seated twist": "Giro sentado con barra",
  "barbell shrug": " con barra",
  "barbell side bent v. 2": " con barra",
  "barbell side split squat": "Sentadilla lateral búlgara con barra",
  "barbell side split squat v. 2": "Sentadilla lateral búlgara v. 2 con barra",
  "barbell single leg deadlift": "Peso muerto una pierna con barra",
  "barbell single leg split squat": "Sentadilla una pierna búlgara con barra",
  "barbell sitted alternate leg raise": "Elevación de piernas sitted alterno con barra",
  "barbell sitted alternate leg raise (female)": "Elevación de piernas alterna sentado",
  "barbell skier": " con barra",
  "barbell speed squat": "Sentadilla speed con barra",
  "barbell split squat v. 2": "Sentadilla búlgara v. 2 con barra",
  "barbell squat (on knees)": "Sentadilla con barra",
  "barbell squat jump step rear lunge": "Sentadilla jump step rear zancada con barra",
  "barbell standing ab rollerout": " con barra",
  "barbell standing back wrist curl": "Curl de muñeca de pie espalda con barra",
  "barbell standing bradford press": "Press de pie bradford con barra",
  "barbell standing calf raise": "Elevación de pantorrillas de pie con barra",
  "barbell standing close grip curl": "Curl de pie agarre cerrado con barra",
  "barbell standing close grip military press": "Press de pie agarre cerrado military con barra",
  "barbell standing concentration curl": "Curl de pie concentration con barra",
  "barbell standing front raise over head": "Elevación de pie frontal over head con barra",
  "barbell standing leg calf raise": "Elevación de pantorrillas de pie pierna con barra",
  "barbell standing overhead triceps extension": "Extensión de tríceps de pie sobre la cabeza con barra",
  "barbell standing reverse grip curl": "Curl de pie agarre inverso con barra",
  "barbell standing rocking leg calf raise": "Elevación de pantorrillas de pie rocking pierna con barra",
  "barbell standing twist": "Giro de pie con barra",
  "barbell standing wide grip biceps curl": "Curl de bíceps de pie agarre amplio con barra",
  "barbell standing wide military press": "Press de pie amplio military con barra",
  "barbell standing wide-grip curl": "Curl de pie agarre amplio con barra",
  "barbell step-up": "Subida a cajón con barra",
  "barbell stiff leg good morning": " con barra",
  "barbell straight leg deadlift": "Peso muerto recto pierna con barra",
  "barbell sumo deadlift": "Peso muerto sumo con barra",
  "barbell thruster": "Thruster con barra",
  "barbell upright row": "Remo upright con barra",
  "barbell upright row v. 2": "Remo upright v. 2 con barra",
  "barbell upright row v. 3": "Remo upright v. 3 con barra",
  "barbell wide bench press": "Press de banca amplio con barra",
  "barbell wide reverse grip bench press": "Press de banca amplio agarre inverso con barra",
  "barbell wide squat": "Sentadilla amplio con barra",
  "barbell wide-grip upright row": "Remo agarre amplio upright con barra",
  "barbell wrist curl": "Curl de muñeca con barra",
  "barbell wrist curl v. 2": "Curl de muñeca v. 2 con barra",
  "barbell zercher squat": "Sentadilla zercher con barra",
  "basic toe touch (male)": "Toque de puntas basic (Male)",
  "battling ropes": "",
  "bear crawl": "Caminata de oso",
  "behind head chest stretch": "Estiramiento de pecho por detrás head",
  "bench dip (knees bent)": "Fondo en banco",
  "bench dip on floor": "Fondo floor con banco",
  "bench hip extension": "Extensión de cadera con banco",
  "bench pull-ups": "Dominadas con banco",
  "bent knee lying twist (male)": "Giro flexionado knee acostado (Male)",
  "biceps leg concentration curl": "Curl bíceps pierna concentration",
  "biceps narrow pull-ups": "Dominadas bíceps narrow",
  "biceps pull-up": "Dominada bíceps",
  "body-up": "",
  "bodyweight drop jump squat": "Sentadilla con salto",
  "bodyweight incline side plank": "Plancha lateral inclinada",
  "bodyweight kneeling triceps extension": "Extensión de tríceps bodyweight de rodillas",
  "bodyweight side lying biceps curl": "Curl de bíceps bodyweight lateral acostado",
  "bodyweight squatting row": "Remo bodyweight squatting",
  "bodyweight squatting row (with towel)": "Remo bodyweight squatting (Towel)",
  "bodyweight standing calf raise": "Elevación de pantorrillas bodyweight de pie",
  "bodyweight standing close-grip one arm row": "Remo bodyweight de pie agarre cerrado un brazo",
  "bodyweight standing close-grip row": "Remo bodyweight de pie agarre cerrado",
  "bodyweight standing one arm row": "Remo bodyweight de pie un brazo",
  "bodyweight standing one arm row (with towel)": "Remo bodyweight de pie un brazo (Towel)",
  "bodyweight standing row": "Remo bodyweight de pie",
  "bodyweight standing row (with towel)": "Remo bodyweight de pie (Towel)",
  "bottoms-up": "",
  "box jump down with one leg stabilization": " con cajón",
  "bridge - mountain climber (cross body)": "Puente - mountain climber (Cross body)",
  "burpee": "Burpee",
  "butt-ups": "",
  "butterfly yoga pose": "Postura de mariposa de yoga",
  "cable alternate shoulder press": "Press de hombros alterno con polea",
  "cable alternate triceps extension": "Extensión de tríceps alterno con polea",
  "cable assisted inverse leg curl": "Curl de piernas asistido inverse con polea",
  "cable bar lateral pulldown": "Jalón bar lateral con polea",
  "cable bench press": "Press de banca con polea",
  "cable close grip curl": "Curl agarre cerrado con polea",
  "cable concentration curl": "Curl concentration con polea",
  "cable concentration extension (on knee)": "Extensión concentration con polea (Knee)",
  "cable cross-over lateral pulldown": "Jalón cross-over lateral con polea",
  "cable cross-over revers fly": "Apertura posterior cruzada en polea",
  "cable cross-over variation": " con polea",
  "cable curl": "Curl con polea",
  "cable deadlift": "Peso muerto con polea",
  "cable decline fly": "Apertura declinado con polea",
  "cable decline one arm press": "Press declinado un brazo con polea",
  "cable decline press": "Press declinado con polea",
  "cable decline seated wide-grip row": "Remo declinado sentado agarre amplio con polea",
  "cable drag curl": "Curl drag con polea",
  "cable floor seated wide-grip row": "Remo floor sentado agarre amplio con polea",
  "cable forward raise": "Elevación forward con polea",
  "cable front raise": "Elevación frontal en polea",
  "cable front shoulder raise": "Elevación de hombros frontal con polea",
  "cable hammer curl (with rope)": "Curl martillo en polea",
  "cable high pulley overhead tricep extension": "Extensión de tríceps alta pulley sobre la cabeza con polea",
  "cable high row (kneeling)": "Remo alta con polea (De rodillas)",
  "cable hip adduction": "Adducción de cadera en polea",
  "cable incline bench press": "Press de banca inclinado con polea",
  "cable incline bench row": "Remo inclinado bench con polea",
  "cable incline fly": "Apertura inclinado con polea",
  "cable incline fly (on stability ball)": "Apertura inclinado con polea (Stability ball)",
  "cable incline pushdown": " con polea",
  "cable incline triceps extension": "Extensión de tríceps inclinado en polea",
  "cable judo flip": " con polea",
  "cable kickback": "Patada en polea",
  "cable kneeling crunch": "Crunch de rodillas con polea",
  "cable kneeling rear delt row (with rope) (male)": "Remo de rodillas rear delt con polea (Rope, Male)",
  "cable kneeling triceps extension": "Extensión de tríceps de rodillas con polea",
  "cable lat pulldown full range of motion": "Jalón de dorsales completa range motion con polea",
  "cable lateral pulldown (with rope attachment)": "Jalón lateral con polea (Rope attachment)",
  "cable lateral pulldown with v-bar": "Jalón lateral v-bar con polea",
  "cable lateral raise": "Elevación lateral en polea",
  "cable low fly": "Apertura bajo con polea",
  "cable low seated row": "Remo bajo sentado con polea",
  "cable lying bicep curl": "Curl acostado bicep con polea",
  "cable lying close-grip curl": "Curl acostado agarre cerrado con polea",
  "cable lying extension pullover (with rope attachment)": "Extensión acostado pullover con polea (Rope attachment)",
  "cable lying fly": "Apertura acostado con polea",
  "cable lying triceps extension v. 2": "Extensión de tríceps acostado v. 2 con polea",
  "cable middle fly": "Apertura middle con polea",
  "cable one arm bent over row": "Remo inclinado un brazo con polea",
  "cable one arm curl": "Curl un brazo con polea",
  "cable one arm decline chest fly": "Apertura de pecho un brazo declinado con polea",
  "cable one arm fly on exercise ball": "Apertura un brazo exercise ball con polea",
  "cable one arm incline fly on exercise ball": "Apertura un brazo inclinado exercise ball con polea",
  "cable one arm incline press": "Press un brazo inclinado con polea",
  "cable one arm incline press on exercise ball": "Press un brazo inclinado exercise ball con polea",
  "cable one arm lateral bent-over": " con polea",
  "cable one arm lateral raise": "Elevación un brazo lateral con polea",
  "cable one arm preacher curl": "Curl un brazo preacher con polea",
  "cable one arm press on exercise ball": "Press un brazo exercise ball con polea",
  "cable one arm pulldown": "Jalón un brazo con polea",
  "cable one arm reverse preacher curl": "Curl un brazo invertido preacher con polea",
  "cable one arm straight back high row (kneeling)": "Remo un brazo recto espalda alta con polea (De rodillas)",
  "cable one arm tricep pushdown": " con polea",
  "cable overhead curl": "Curl sobre la cabeza con polea",
  "cable overhead curl on exercise ball": "Curl sobre la cabeza exercise ball con polea",
  "cable overhead triceps extension (rope attachment)": "Extensión de tríceps sobre la cabeza con polea (Rope attachment)",
  "cable palm rotational row": "Remo palm rotational con polea",
  "cable preacher curl": "Curl preacher con polea",
  "cable press on exercise ball": "Press exercise ball con polea",
  "cable pull through (with rope)": "Jalón through con polea (Rope)",
  "cable pulldown": "Jalón en polea",
  "cable pulldown (pro lat bar)": "Jalón en polea",
  "cable pulldown bicep curl": "Jalón bicep curl con polea",
  "cable pushdown": " con polea",
  "cable pushdown (straight arm) v. 2": " con polea (Recto brazo)",
  "cable pushdown (with rope attachment)": " con polea (Rope attachment)",
  "cable rear delt row (stirrups)": "Remo rear delt con polea (Stirrups)",
  "cable rear delt row (with rope)": "Remo rear delt con polea (Rope)",
  "cable rear drive": " con polea",
  "cable rear pulldown": "Jalón rear con polea",
  "cable reverse crunch": "Crunch invertido en polea",
  "cable reverse curl": "Curl invertido con polea",
  "cable reverse grip triceps pushdown (sz-bar) (with arm blaster)": " con polea (Sz-bar, Brazo blaster)",
  "cable reverse one arm curl": "Curl invertido un brazo con polea",
  "cable reverse preacher curl": "Curl invertido preacher con polea",
  "cable reverse wrist curl": "Curl de muñeca invertido con polea",
  "cable reverse-grip pushdown": " con polea",
  "cable reverse-grip straight back seated high row": "Remo agarre inverso recto espalda sentado alta con polea",
  "cable rope crossover seated row": "Remo rope crossover sentado con polea",
  "cable rope elevated seated row": "Remo rope elevated sentado con polea",
  "cable rope extension incline bench row": "Extensión rope inclinado bench remo con polea",
  "cable rope hammer preacher curl": "Curl rope hammer preacher con polea",
  "cable rope high pulley overhead tricep extension": "Extensión de tríceps rope alta pulley sobre la cabeza con polea",
  "cable rope incline tricep extension": "Extensión de tríceps rope inclinado con polea",
  "cable rope lying on floor tricep extension": "Extensión de tríceps rope acostado floor con polea",
  "cable rope one arm hammer preacher curl": "Curl rope un brazo hammer preacher con polea",
  "cable rope seated row": "Remo rope sentado con polea",
  "cable russian twists (on stability ball)": "Giros russian con polea (Stability ball)",
  "cable seated chest press": "Press sentado pecho con polea",
  "cable seated crunch": "Crunch sentado con polea",
  "cable seated curl": "Curl sentado con polea",
  "cable seated high row (v-bar)": "Remo sentado alta con polea (V-bar)",
  "cable seated one arm alternate row": "Remo sentado un brazo alterno con polea",
  "cable seated one arm concentration curl": "Curl sentado un brazo concentration con polea",
  "cable seated overhead curl": "Curl sentado sobre la cabeza con polea",
  "cable seated rear lateral raise": "Elevación sentado rear lateral con polea",
  "cable seated row": "Remo sentado con polea",
  "cable seated shoulder internal rotation": "Rotación sentado hombro internal con polea",
  "cable seated twist": "Giro sentado con polea",
  "cable seated wide-grip row": "Remo sentado agarre amplio con polea",
  "cable shoulder press": "Press de hombros con polea",
  "cable shrug": " con polea",
  "cable side bend": " con polea",
  "cable side bend crunch (bosu ball)": "Crunch lateral bend con polea (Bosu ball)",
  "cable side crunch": "Crunch lateral con polea",
  "cable squat row (with rope attachment)": "Sentadilla remo con polea (Rope attachment)",
  "cable squatting curl": "Curl squatting con polea",
  "cable standing back wrist curl": "Curl de muñeca de pie espalda con polea",
  "cable standing calf raise": "Elevación de pantorrillas de pie con polea",
  "cable standing cross-over high reverse fly": "Apertura de pie cross-over alta invertido con polea",
  "cable standing crunch": "Crunch de pie con polea",
  "cable standing crunch (with rope attachment)": "Crunch de pie con polea (Rope attachment)",
  "cable standing fly": "Apertura de pie con polea",
  "cable standing hip extension": "Extensión de cadera de pie con polea",
  "cable standing inner curl": "Curl de pie inner con polea",
  "cable standing lift": " con polea",
  "cable standing one arm triceps extension": "Extensión de tríceps de pie un brazo con polea",
  "cable standing one leg calf raise": "Elevación de pantorrillas de pie una pierna con polea",
  "cable standing pulldown (with rope)": "Jalón de pie con polea (Rope)",
  "cable standing rear delt row (with rope)": "Remo de pie rear delt con polea (Rope)",
  "cable standing reverse grip one arm overhead tricep extension": "Extensión de tríceps por encima de la cabeza a un brazo en polea",
  "cable standing row (v-bar)": "Remo de pie con polea (V-bar)",
  "cable standing shoulder external rotation": "Rotación de pie hombro external con polea",
  "cable standing twist row (v-bar)": "Giro de pie remo con polea (V-bar)",
  "cable standing up straight crossovers": " con polea",
  "cable straight arm pulldown": "Jalón recto brazo con polea",
  "cable straight arm pulldown (with rope)": "Jalón recto brazo con polea (Rope)",
  "cable straight back seated row": "Remo recto espalda sentado con polea",
  "cable supine reverse fly": "Apertura boca arriba invertido con polea",
  "cable thibaudeau kayak row": "Remo thibaudeau kayak con polea",
  "cable triceps pushdown (v-bar)": " con polea (V-bar)",
  "cable triceps pushdown (v-bar) (with arm blaster)": " con polea (V-bar, Brazo blaster)",
  "cable tuck reverse crunch": "Crunch tuck invertido con polea",
  "cable twist": "Giro con polea",
  "cable twist (up-down)": "Giro con polea (Up-down)",
  "cable twisting pull": "Jalón con giro con polea",
  "cable two arm curl on incline bench": "Curl two brazo inclinado bench con polea",
  "cable two arm tricep kickback": "Patada de tríceps a dos brazos en polea",
  "cable underhand pulldown": "Jalón agarre supino con polea",
  "cable upper chest crossovers": " con polea",
  "cable upper row": "Remo superior con polea",
  "cable upright row": "Remo upright con polea",
  "cable wide grip rear pulldown behind neck": "Jalón agarre amplio rear por detrás cuello con polea",
  "cable wrist curl": "Curl de muñeca con polea",
  "calf push stretch with hands against wall": "Estiramiento pantorrilla empuje hands wall",
  "calf stretch with hands against wall": "Estiramiento pantorrilla hands wall",
  "calf stretch with rope": "Estiramiento pantorrilla rope",
  "cambered bar lying row": "Remo cambered bar acostado",
  "captains chair straight leg raise": "Elevación de piernas captains chair recto",
  "chair leg extended stretch": "Estiramiento chair pierna extended",
  "chest and front of shoulder stretch": "Estiramiento de hombros pecho frontal",
  "chest dip": "Fondo de pecho",
  "chest dip (on dip-pull-up cage)": "Fondo de pecho",
  "chest dip on straight bar": "Fondo de pecho recto bar",
  "chest stretch with exercise ball": "Estiramiento de pecho exercise ball",
  "chest tap push-up (male)": "Flexión pecho tap (Male)",
  "chin-up": "Dominada supina",
  "chin-ups (narrow parallel grip)": "Dominadas supinas",
  "circles knee stretch": "Estiramiento circles knee",
  "clap push up": "Empuje clap up",
  "clock push-up": "Flexión clock",
  "close grip chin-up": "",
  "close-grip push-up": "Flexión agarre cerrado",
  "close-grip push-up (on knees)": "Flexión agarre cerrado (Knees)",
  "cocoons": "",
  "crab twist toe touch": "Toque de puntas crab giro",
  "cross body crunch": "Crunch cross body",
  "crunch (hands overhead)": "Crunch",
  "crunch (on stability ball)": "Crunch",
  "crunch (on stability ball, arms straight)": "Crunch",
  "crunch floor": "Crunch en el suelo",
  "curl-up": "Curl up",
  "curtsey squat": "Sentadilla curtsey",
  "cycle cross trainer": "",
  "dead bug": "Bicho muerto",
  "decline crunch": "Crunch declinado",
  "decline push-up": "Flexión declinada",
  "decline sit-up": "Abdominal declinado",
  "deep push up": "Empuje deep up",
  "diamond push-up": "Flexión de diamante",
  "donkey calf raise": "Elevación de pantorrillas donkey",
  "drop push up": "Empuje drop up",
  "dumbbell alternate biceps curl": "Curl de bíceps alterno con mancuernas",
  "dumbbell alternate biceps curl (with arm blaster)": "Curl de bíceps alterno con mancuernas (Brazo blaster)",
  "dumbbell alternate hammer preacher curl": "Curl alterno hammer preacher con mancuernas",
  "dumbbell alternate preacher curl": "Curl alterno preacher con mancuernas",
  "dumbbell alternate seated hammer curl": "Curl alterno sentado hammer con mancuernas",
  "dumbbell alternate side press": "Press alterno lateral con mancuernas",
  "dumbbell alternating bicep curl with leg raised on exercise ball": "Curl alterno bicep pierna raised exercise ball con mancuernas",
  "dumbbell alternating seated bicep curl on exercise ball": "Curl alterno sentado bicep exercise ball con mancuernas",
  "dumbbell arnold press": "Press Arnold con mancuernas",
  "dumbbell arnold press v. 2": "Press arnold v. 2 con mancuernas",
  "dumbbell around pullover": " con mancuernas",
  "dumbbell bench press": "Press de banca con mancuernas",
  "dumbbell bench seated press": "Press bench sentado con mancuernas",
  "dumbbell bench squat": "Sentadilla bench con mancuernas",
  "dumbbell bent over row": "Remo inclinado con mancuernas",
  "dumbbell bicep curl lunge with bowling motion": "Zancada bicep curl bowling motion con mancuernas",
  "dumbbell bicep curl on exercise ball with leg raised": "Curl bicep exercise ball pierna raised con mancuernas",
  "dumbbell bicep curl with stork stance": "Curl bicep stork stance con mancuernas",
  "dumbbell biceps curl": "Curl de bíceps con mancuernas",
  "dumbbell biceps curl (with arm blaster)": "Curl de bíceps con mancuernas (Brazo blaster)",
  "dumbbell biceps curl reverse": "Curl de bíceps invertido con mancuernas",
  "dumbbell biceps curl squat": "Curl de bíceps sentadilla con mancuernas",
  "dumbbell biceps curl v sit on bosu ball": "Curl de bíceps sit bosu ball con mancuernas",
  "dumbbell burpee": " con mancuernas",
  "dumbbell clean": "Cargada con mancuernas",
  "dumbbell close grip press": "Press agarre cerrado con mancuernas",
  "dumbbell close-grip press": "Press agarre cerrado con mancuernas",
  "dumbbell concentration curl": "Curl concentration con mancuernas",
  "dumbbell contralateral forward lunge": "Zancada contralateral forward con mancuernas",
  "dumbbell cross body hammer curl": "Curl cross body hammer con mancuernas",
  "dumbbell cross body hammer curl v. 2": "Curl cross body hammer v. 2 con mancuernas",
  "dumbbell cuban press": "Press cuban con mancuernas",
  "dumbbell cuban press v. 2": "Press cuban v. 2 con mancuernas",
  "dumbbell deadlift": "Peso muerto con mancuernas",
  "dumbbell decline bench press": "Press de banca declinado con mancuernas",
  "dumbbell decline fly": "Apertura declinado con mancuernas",
  "dumbbell decline hammer press": "Press declinado hammer con mancuernas",
  "dumbbell decline one arm fly": "Apertura declinado un brazo con mancuernas",
  "dumbbell decline one arm hammer press": "Press martillo declinado a un brazo con mancuernas",
  "dumbbell decline shrug": " con mancuernas",
  "dumbbell decline shrug v. 2": " con mancuernas",
  "dumbbell decline triceps extension": "Extensión de tríceps declinado con mancuernas",
  "dumbbell decline twist fly": "Giro declinado apertura con mancuernas",
  "dumbbell finger curls": " con mancuernas",
  "dumbbell fly": "Apertura con mancuernas",
  "dumbbell fly on exercise ball": "Apertura exercise ball con mancuernas",
  "dumbbell forward lunge triceps extension": "Extensión de tríceps forward zancada con mancuernas",
  "dumbbell front raise": "Elevación frontal con mancuernas",
  "dumbbell front raise v. 2": "Elevación frontal v. 2 con mancuernas",
  "dumbbell full can lateral raise": "Elevación completa can lateral con mancuernas",
  "dumbbell goblet squat": "Sentadilla goblet con mancuernas",
  "dumbbell hammer curl": "Curl martillo con mancuernas",
  "dumbbell hammer curl on exercise ball": "Curl hammer exercise ball con mancuernas",
  "dumbbell hammer curl v. 2": "Curl hammer v. 2 con mancuernas",
  "dumbbell hammer curls (with arm blaster)": " con mancuernas (Brazo blaster)",
  "dumbbell high curl": "Curl alta con mancuernas",
  "dumbbell incline alternate press": "Press inclinado alterno con mancuernas",
  "dumbbell incline bench press": "Press de banca inclinado con mancuernas",
  "dumbbell incline biceps curl": "Curl de bíceps inclinado con mancuernas",
  "dumbbell incline breeding": " con mancuernas",
  "dumbbell incline curl": "Curl inclinado con mancuernas",
  "dumbbell incline curl v. 2": "Curl inclinado v. 2 con mancuernas",
  "dumbbell incline fly": "Apertura inclinado con mancuernas",
  "dumbbell incline fly on exercise ball": "Apertura inclinado exercise ball con mancuernas",
  "dumbbell incline hammer curl": "Curl inclinado hammer con mancuernas",
  "dumbbell incline hammer press": "Press inclinado hammer con mancuernas",
  "dumbbell incline hammer press on exercise ball": "Press inclinado hammer exercise ball con mancuernas",
  "dumbbell incline inner biceps curl": "Curl de bíceps inclinado inner con mancuernas",
  "dumbbell incline one arm fly": "Apertura inclinado un brazo con mancuernas",
  "dumbbell incline one arm fly on exercise ball": "Apertura inclinado un brazo exercise ball con mancuernas",
  "dumbbell incline one arm hammer press": "Press inclinado un brazo hammer con mancuernas",
  "dumbbell incline one arm hammer press on exercise ball": "Press inclinado un brazo hammer exercise ball con mancuernas",
  "dumbbell incline one arm lateral raise": "Elevación inclinado un brazo lateral con mancuernas",
  "dumbbell incline one arm press": "Press inclinado un brazo con mancuernas",
  "dumbbell incline one arm press on exercise ball": "Press inclinado un brazo exercise ball con mancuernas",
  "dumbbell incline palm-in press": "Press inclinado palm-in con mancuernas",
  "dumbbell incline press on exercise ball": "Press inclinado exercise ball con mancuernas",
  "dumbbell incline raise": "Elevación inclinado con mancuernas",
  "dumbbell incline rear lateral raise": "Elevación inclinado rear lateral con mancuernas",
  "dumbbell incline row": "Remo inclinado con mancuernas",
  "dumbbell incline shoulder raise": "Elevación de hombros inclinado con mancuernas",
  "dumbbell incline shrug": " con mancuernas",
  "dumbbell incline t-raise": " con mancuernas",
  "dumbbell incline triceps extension": "Extensión de tríceps inclinado con mancuernas",
  "dumbbell incline twisted flyes": " con mancuernas",
  "dumbbell incline two arm extension": "Extensión inclinado two brazo con mancuernas",
  "dumbbell incline y-raise": " con mancuernas",
  "dumbbell iron cross": " con mancuernas",
  "dumbbell kickback": "Patada con mancuernas",
  "dumbbell kickbacks on exercise ball": "Patadas exercise ball con mancuernas",
  "dumbbell kneeling bicep curl exercise ball": "Curl de rodillas bicep exercise ball con mancuernas",
  "dumbbell lateral raise": "Elevación lateral con mancuernas",
  "dumbbell lateral to front raise": "Elevación lateral frontal con mancuernas",
  "dumbbell lunge": "Zancada con mancuernas",
  "dumbbell lunge with bicep curl": "Zancada bicep curl con mancuernas",
  "dumbbell lying extension (across face)": "Extensión acostado con mancuernas (Across face)",
  "dumbbell lying alternate extension": "Extensión acostado alterno con mancuernas",
  "dumbbell lying elbow press": "Press acostado elbow con mancuernas",
  "dumbbell lying external shoulder rotation": "Rotación acostado external hombro con mancuernas",
  "dumbbell lying femoral": " con mancuernas",
  "dumbbell lying hammer press": "Press acostado hammer con mancuernas",
  "dumbbell lying on floor rear delt raise": "Elevación acostado floor rear delt con mancuernas",
  "dumbbell lying one arm deltoid rear": " con mancuernas",
  "dumbbell lying one arm press": "Press acostado un brazo con mancuernas",
  "dumbbell lying one arm press v. 2": "Press acostado un brazo v. 2 con mancuernas",
  "dumbbell lying one arm pronated triceps extension": "Extensión de tríceps acostado un brazo pronated con mancuernas",
  "dumbbell lying one arm rear lateral raise": "Elevación acostado un brazo rear lateral con mancuernas",
  "dumbbell lying one arm supinated triceps extension": "Extensión de tríceps acostado un brazo supinated con mancuernas",
  "dumbbell lying pronation": " con mancuernas",
  "dumbbell lying pronation on floor": " con mancuernas",
  "dumbbell lying pullover on exercise ball": " con mancuernas",
  "dumbbell lying rear delt row": "Remo acostado rear delt con mancuernas",
  "dumbbell lying rear lateral raise": "Elevación acostado rear lateral con mancuernas",
  "dumbbell lying single extension": "Extensión acostado una con mancuernas",
  "dumbbell lying supination": " con mancuernas",
  "dumbbell lying supination on floor": " con mancuernas",
  "dumbbell lying supine biceps curl": "Curl de bíceps acostado boca arriba con mancuernas",
  "dumbbell lying supine curl": "Curl acostado boca arriba con mancuernas",
  "dumbbell lying triceps extension": "Extensión de tríceps acostado con mancuernas",
  "dumbbell lying wide curl": "Curl acostado amplio con mancuernas",
  "dumbbell neutral grip bench press": "Press de banca agarre neutro grip con mancuernas",
  "dumbbell one arm bench fly": "Apertura un brazo bench con mancuernas",
  "dumbbell one arm bent-over row": "Remo inclinado un brazo con mancuernas",
  "dumbbell one arm chest fly on exercise ball": "Apertura de pecho un brazo exercise ball con mancuernas",
  "dumbbell one arm concentration curl (on stability ball)": "Curl un brazo concentration con mancuernas (Stability ball)",
  "dumbbell one arm decline chest press": "Press un brazo declinado pecho con mancuernas",
  "dumbbell one arm fly on exercise ball": "Apertura un brazo exercise ball con mancuernas",
  "dumbbell one arm french press on exercise ball": "Press un brazo french exercise ball con mancuernas",
  "dumbbell one arm hammer preacher curl": "Curl un brazo hammer preacher con mancuernas",
  "dumbbell one arm hammer press on exercise ball": "Press un brazo hammer exercise ball con mancuernas",
  "dumbbell one arm incline chest press": "Press un brazo inclinado pecho con mancuernas",
  "dumbbell one arm kickback": "Patada un brazo con mancuernas",
  "dumbbell one arm lateral raise": "Elevación un brazo lateral con mancuernas",
  "dumbbell one arm lateral raise with support": "Elevación un brazo lateral support con mancuernas",
  "dumbbell one arm press on exercise ball": "Press un brazo exercise ball con mancuernas",
  "dumbbell one arm prone curl": "Curl un brazo boca abajo con mancuernas",
  "dumbbell one arm prone hammer curl": "Curl un brazo boca abajo hammer con mancuernas",
  "dumbbell one arm pullover on exercise ball": " con mancuernas",
  "dumbbell one arm reverse wrist curl": "Curl de muñeca invertido a un brazo con mancuernas",
  "dumbbell one arm reverse fly (with support)": "Apertura un brazo invertido con mancuernas (Support)",
  "dumbbell one arm reverse grip press": "Press un brazo agarre inverso con mancuernas",
  "dumbbell one arm reverse preacher curl": "Curl un brazo invertido preacher con mancuernas",
  "dumbbell one arm reverse spider curl": "Curl un brazo invertido spider con mancuernas",
  "dumbbell one arm seated bicep curl on exercise ball": "Curl un brazo sentado bicep exercise ball con mancuernas",
  "dumbbell one arm seated hammer curl": "Curl un brazo sentado hammer con mancuernas",
  "dumbbell one arm seated neutral wrist curl": "Curl de muñeca un brazo sentado agarre neutro con mancuernas",
  "dumbbell one arm shoulder press": "Press de hombros un brazo con mancuernas",
  "dumbbell one arm shoulder press v. 2": "Press de hombros un brazo v. 2 con mancuernas",
  "dumbbell one arm snatch": "Arranque un brazo con mancuernas",
  "dumbbell one arm standing curl": "Curl un brazo de pie con mancuernas",
  "dumbbell one arm standing hammer curl": "Curl un brazo de pie hammer con mancuernas",
  "dumbbell one arm triceps extension (on bench)": "Extensión de tríceps un brazo con mancuernas (Bench)",
  "dumbbell one arm upright row": "Remo un brazo upright con mancuernas",
  "dumbbell one arm wrist curl": "Curl de muñeca un brazo con mancuernas",
  "dumbbell one arm zottman preacher curl": "Curl un brazo zottman preacher con mancuernas",
  "dumbbell one leg fly on exercise ball": "Apertura una pierna exercise ball con mancuernas",
  "dumbbell over bench neutral wrist curl": "Curl de muñeca over bench agarre neutro con mancuernas",
  "dumbbell over bench one arm neutral wrist curl": "Curl de muñeca over bench un brazo agarre neutro con mancuernas",
  "dumbbell over bench one arm reverse wrist curl": "Curl de muñeca over bench un brazo invertido con mancuernas",
  "dumbbell over bench one arm wrist curl": "Curl de muñeca over bench un brazo con mancuernas",
  "dumbbell over bench revers wrist curl": "Curl de muñeca over bench revers con mancuernas",
  "dumbbell over bench wrist curl": "Curl de muñeca over bench con mancuernas",
  "dumbbell palm rotational bent over row": "Remo inclinado palm rotational con mancuernas",
  "dumbbell palms in incline bench press": "Press de banca palms inclinado con mancuernas",
  "dumbbell peacher hammer curl": "Curl peacher hammer con mancuernas",
  "dumbbell plyo squat": "Sentadilla explosiva con mancuernas",
  "dumbbell preacher curl": "Curl preacher con mancuernas",
  "dumbbell preacher curl over exercise ball": "Curl preacher over exercise ball con mancuernas",
  "dumbbell press on exercise ball": "Press exercise ball con mancuernas",
  "dumbbell pronate-grip triceps extension": "Extensión de tríceps pronate-grip con mancuernas",
  "dumbbell prone incline curl": "Curl boca abajo inclinado con mancuernas",
  "dumbbell prone incline hammer curl": "Curl boca abajo inclinado hammer con mancuernas",
  "dumbbell pullover": " con mancuernas",
  "dumbbell pullover hip extension on exercise ball": "Extensión de cadera pullover exercise ball con mancuernas",
  "dumbbell pullover on exercise ball": " con mancuernas",
  "dumbbell push press": "Press empuje con mancuernas",
  "dumbbell raise": "Elevación con mancuernas",
  "dumbbell rear delt raise": "Elevación rear delt con mancuernas",
  "dumbbell rear delt row_shoulder": " con mancuernas",
  "dumbbell rear fly": "Apertura rear con mancuernas",
  "dumbbell rear lateral raise": "Elevación rear lateral con mancuernas",
  "dumbbell rear lateral raise (support head)": "Elevación rear lateral con mancuernas (Support head)",
  "dumbbell rear lunge": "Zancada rear con mancuernas",
  "dumbbell revers grip biceps curl": "Curl de bíceps revers grip con mancuernas",
  "dumbbell reverse bench press": "Press de banca invertido con mancuernas",
  "dumbbell reverse fly": "Apertura posterior con mancuernas",
  "dumbbell reverse grip incline bench one arm row": "Remo agarre inverso inclinado bench un brazo con mancuernas",
  "dumbbell reverse grip incline bench two arm row": "Remo agarre inverso inclinado bench two brazo con mancuernas",
  "dumbbell reverse grip row (female)": "Remo agarre inverso con mancuernas",
  "dumbbell reverse preacher curl": "Curl invertido preacher con mancuernas",
  "dumbbell reverse spider curl": "Curl invertido spider con mancuernas",
  "dumbbell reverse wrist curl": "Curl de muñeca invertido con mancuernas",
  "dumbbell romanian deadlift": "Peso muerto romanian con mancuernas",
  "dumbbell rotation reverse fly": "Rotación invertido apertura con mancuernas",
  "dumbbell scott press": "Press scott con mancuernas",
  "dumbbell seated alternate front raise": "Elevación sentado alterno frontal con mancuernas",
  "dumbbell seated alternate hammer curl on exercise ball": "Curl sentado alterno hammer exercise ball con mancuernas",
  "dumbbell seated alternate press": "Press sentado alterno con mancuernas",
  "dumbbell seated alternate shoulder": " con mancuernas",
  "dumbbell seated bench extension": "Extensión sentado bench con mancuernas",
  "dumbbell seated bent arm lateral raise": "Elevación sentado flexionado brazo lateral con mancuernas",
  "dumbbell seated bent over alternate kickback": "Patada sentado flexionado over alterno con mancuernas",
  "dumbbell seated bent over triceps extension": "Extensión de tríceps sentado flexionado over con mancuernas",
  "dumbbell seated bicep curl": "Curl sentado bicep con mancuernas",
  "dumbbell seated biceps curl (on stability ball)": "Curl de bíceps sentado con mancuernas (Stability ball)",
  "dumbbell seated biceps curl to shoulder press": "Press de hombros sentado bíceps curl con mancuernas",
  "dumbbell seated calf raise": "Elevación de pantorrillas sentado con mancuernas",
  "dumbbell seated curl": "Curl sentado con mancuernas",
  "dumbbell seated front raise": "Elevación sentado frontal con mancuernas",
  "dumbbell seated hammer curl": "Curl sentado hammer con mancuernas",
  "dumbbell seated inner biceps curl": "Curl de bíceps sentado inner con mancuernas",
  "dumbbell seated kickback": "Patada sentado con mancuernas",
  "dumbbell seated lateral raise": "Elevación sentado lateral con mancuernas",
  "dumbbell seated lateral raise v. 2": "Elevación sentado lateral v. 2 con mancuernas",
  "dumbbell seated neutral wrist curl": "Curl de muñeca sentado agarre neutro con mancuernas",
  "dumbbell seated one arm bicep curl on exercise ball with leg raised": "Curl sentado un brazo bicep exercise ball pierna raised con mancuernas",
  "dumbbell seated one arm kickback": "Patada sentado un brazo con mancuernas",
  "dumbbell seated one arm rotate": " con mancuernas",
  "dumbbell seated one leg calf raise": "Elevación de pantorrillas sentado una pierna con mancuernas",
  "dumbbell seated one leg calf raise - hammer grip": "Elevación de pantorrillas sentado una pierna - hammer grip con mancuernas",
  "dumbbell seated one leg calf raise - palm up": "Elevación de pantorrillas sentado una pierna - palm up con mancuernas",
  "dumbbell seated palms up wrist curl": "Curl de muñeca sentado palms up con mancuernas",
  "dumbbell seated preacher curl": "Curl sentado preacher con mancuernas",
  "dumbbell seated revers grip concentration curl": "Curl sentado revers grip concentration con mancuernas",
  "dumbbell seated reverse grip one arm overhead tricep extension": "Extensión de tríceps sentado agarre inverso un brazo sobre la cabeza con mancuernas",
  "dumbbell seated shoulder press": "Press de hombros sentado con mancuernas",
  "dumbbell seated shoulder press (parallel grip)": "Press de hombros sentado con mancuernas (Parallel grip)",
  "dumbbell seated triceps extension": "Extensión de tríceps sentado con mancuernas",
  "dumbbell shrug": " con mancuernas",
  "dumbbell side bend": " con mancuernas",
  "dumbbell side lying one hand raise": "Elevación lateral acostado one hand con mancuernas",
  "dumbbell side plank with rear fly": "Plancha lateral con apertura posterior",
  "dumbbell single arm overhead carry": " con mancuernas",
  "dumbbell single leg calf raise": "Elevación de pantorrillas una pierna con mancuernas",
  "dumbbell single leg deadlift": "Peso muerto una pierna con mancuernas",
  "dumbbell single leg deadlift with stepbox support": "Peso muerto una pierna stepbox support con mancuernas",
  "dumbbell single leg split squat": "Sentadilla una pierna búlgara con mancuernas",
  "dumbbell single leg squat": "Sentadilla una pierna con mancuernas",
  "dumbbell squat": "Sentadilla con mancuernas",
  "dumbbell standing alternate hammer curl and press": "Press de pie alterno hammer curl con mancuernas",
  "dumbbell standing alternate overhead press": "Press de pie alterno sobre la cabeza con mancuernas",
  "dumbbell standing alternate raise": "Elevación de pie alterno con mancuernas",
  "dumbbell standing alternating tricep kickback": "Patada de pie alterno tríceps con mancuernas",
  "dumbbell standing around world": " con mancuernas",
  "dumbbell standing bent over one arm triceps extension": "Extensión de tríceps de pie flexionado over un brazo con mancuernas",
  "dumbbell standing bent over two arm triceps extension": "Extensión de tríceps de pie flexionado over two brazo con mancuernas",
  "dumbbell standing biceps curl": "Curl de bíceps de pie con mancuernas",
  "dumbbell standing calf raise": "Elevación de pantorrillas de pie con mancuernas",
  "dumbbell standing concentration curl": "Curl de pie concentration con mancuernas",
  "dumbbell standing front raise above head": "Elevación de pie frontal above head con mancuernas",
  "dumbbell standing inner biceps curl v. 2": "Curl de bíceps de pie inner v. 2 con mancuernas",
  "dumbbell standing kickback": "Patada de pie con mancuernas",
  "dumbbell standing one arm concentration curl": "Curl de pie un brazo concentration con mancuernas",
  "dumbbell standing one arm curl (over incline bench)": "Curl de pie un brazo con mancuernas (Over inclinado bench)",
  "dumbbell standing one arm curl over incline bench": "Curl de pie un brazo over inclinado bench con mancuernas",
  "dumbbell standing one arm extension": "Extensión de pie un brazo con mancuernas",
  "dumbbell standing one arm palm in press": "Press de pie un brazo palm con mancuernas",
  "dumbbell standing one arm reverse curl": "Curl de pie un brazo invertido con mancuernas",
  "dumbbell standing overhead press": "Press de pie sobre la cabeza con mancuernas",
  "dumbbell standing palms in press": "Press de pie palms con mancuernas",
  "dumbbell standing preacher curl": "Curl de pie preacher con mancuernas",
  "dumbbell standing reverse curl": "Curl de pie invertido con mancuernas",
  "dumbbell standing triceps extension": "Extensión de tríceps de pie con mancuernas",
  "dumbbell standing zottman preacher curl": "Curl de pie zottman preacher con mancuernas",
  "dumbbell step up single leg balance with bicep curl": "Curl step up una pierna balance bicep con mancuernas",
  "dumbbell step-up": "Subida a cajón con mancuernas",
  "dumbbell step-up lunge": "Subida a cajón zancada con mancuernas",
  "dumbbell step-up split squat": "Subida a cajón búlgara sentadilla con mancuernas",
  "dumbbell stiff leg deadlift": "Peso muerto stiff pierna con mancuernas",
  "dumbbell straight arm pullover": " con mancuernas",
  "dumbbell straight leg deadlift": "Peso muerto recto pierna con mancuernas",
  "dumbbell sumo pull through": "Jalón sumo through con mancuernas",
  "dumbbell supported squat": "Sentadilla supported con mancuernas",
  "dumbbell tate press": "Press tate con mancuernas",
  "dumbbell tricep kickback with stork stance": "Patada tríceps stork stance con mancuernas",
  "dumbbell twisting bench press": "Press de banca con giro con mancuernas",
  "dumbbell upright row": "Remo upright con mancuernas",
  "dumbbell upright row (back pov)": "Remo upright con mancuernas (Espalda pov)",
  "dumbbell upright shoulder external rotation": "Rotación upright hombro external con mancuernas",
  "dumbbell waiter biceps curl": "Curl de bíceps waiter con mancuernas",
  "dumbbell w-press": " con mancuernas",
  "dumbbell zottman curl": "Curl zottman con mancuernas",
  "dumbbell zottman preacher curl": "Curl zottman preacher con mancuernas",
  "dumbbells seated triceps extension": "Extensión de tríceps sentado con mancuernas",
  "dynamic chest stretch (male)": "Estiramiento de pecho dynamic (Male)",
  "elbow dips": "Fondos elbow",
  "elbow lift - reverse push-up": "Flexión elbow lift - invertido",
  "elbow-to-knee": "",
  "elevator": "Elevador",
  "exercise ball alternating arm ups": " con balón suizo",
  "exercise ball back extension with arms extended": "Extensión de espalda brazos extended con balón suizo",
  "exercise ball back extension with hands behind head": "Extensión de espalda hands por detrás head con balón suizo",
  "exercise ball back extension with knees off ground": "Extensión de espalda knees off ground con balón suizo",
  "exercise ball back extension with rotation": "Extensión de espalda rotación con balón suizo",
  "exercise ball dip": "Fondo con balón suizo",
  "exercise ball hip flexor stretch": "Estiramiento cadera flexor con balón suizo",
  "exercise ball hug": " con balón suizo",
  "exercise ball lat stretch": "Estiramiento dorsal con balón suizo",
  "exercise ball lower back stretch (pyramid)": "Estiramiento de espalda inferior con balón suizo (Pyramid)",
  "exercise ball lying side lat stretch": "Estiramiento acostado lateral dorsal con balón suizo",
  "exercise ball on the wall calf raise": "Elevación de pantorrillas wall con balón suizo",
  "exercise ball on the wall calf raise (tennis ball between ankles)": "Elevación de pantorrillas wall con balón suizo (Tennis ball ankles)",
  "exercise ball on the wall calf raise (tennis ball between knees)": "Elevación de pantorrillas wall con balón suizo (Tennis ball knees)",
  "exercise ball one leg prone lower body rotation": "Rotación una pierna boca abajo inferior body con balón suizo",
  "exercise ball one legged diagonal kick hamstring curl": "Curl de isquiotibiales one legged diagonal kick con balón suizo",
  "exercise ball pike push up": "Empuje pike up con balón suizo",
  "exercise ball prone leg raise": "Elevación de piernas boca abajo con balón suizo",
  "exercise ball seated hamstring stretch": "Estiramiento de isquiotibiales sentado con balón suizo",
  "exercise ball seated triceps stretch": "Estiramiento de tríceps sentado con balón suizo",
  "exercise ball supine triceps extension": "Extensión de tríceps boca arriba con balón suizo",
  "ez bar french press on exercise ball": "Press ez bar french exercise ball",
  "ez bar lying bent arms pullover": "",
  "ez bar lying close grip triceps extension behind head": "Extensión de tríceps ez bar acostado agarre cerrado por detrás head",
  "ez bar reverse grip bent over row": "Remo inclinado ez bar agarre inverso",
  "ez bar seated close grip concentration curl": "Curl ez bar sentado agarre cerrado concentration",
  "ez bar standing french press": "Press ez bar de pie french",
  "ez barbell anti gravity press": "Press anti gravity con barra EZ",
  "ez barbell close grip preacher curl": "Curl agarre cerrado preacher con barra EZ",
  "ez barbell close-grip curl": "Curl agarre cerrado con barra EZ",
  "ez barbell curl": "Curl con barra EZ",
  "ez barbell decline close grip face press": "Press declinado agarre cerrado face con barra EZ",
  "ez barbell decline triceps extension": "Extensión de tríceps declinado con barra EZ",
  "ez barbell incline triceps extension": "Extensión de tríceps inclinado con barra EZ",
  "ez barbell jm bench press": "Press de banca jm con barra EZ",
  "ez barbell reverse grip curl": "Curl agarre inverso con barra EZ",
  "ez barbell reverse grip preacher curl": "Curl agarre inverso preacher con barra EZ",
  "ez barbell seated curls": " con barra EZ",
  "ez barbell seated triceps extension": "Extensión de tríceps sentado con barra EZ",
  "ez barbell spider curl": "Curl spider con barra EZ",
  "ez-bar biceps curl (with arm blaster)": "Curl de bíceps con barra EZ (Brazo blaster)",
  "ez-bar close-grip bench press": "Press de banca agarre cerrado con barra EZ",
  "ez-barbell standing wide grip biceps curl": "Curl de bíceps ez-barbell de pie agarre amplio",
  "farmers walk": "",
  "finger curls": "",
  "flag": "",
  "flexion leg sit up (bent knee)": " (Flexionado knee)",
  "flexion leg sit up (straight arm)": " (Recto brazo)",
  "floor fly (with barbell)": "Apertura en el suelo (con barra)",
  "flutter kicks": "Patadas alternas",
  "forward jump": "",
  "forward lunge (male)": "Zancada forward (Male)",
  "frankenstein squat": "Sentadilla frankenstein",
  "frog crunch": "Crunch frog",
  "frog planche": "",
  "front lever": "",
  "front lever reps": "",
  "front plank with twist": "Plancha frontal con giro",
  "full maltese": "",
  "full planche": "",
  "full planche push-up": "Flexión completa planche",
  "gironda sternum chin": "",
  "glute bridge march": "Puente de glúteos march",
  "glute bridge two legs on bench (male)": "Puente de glúteos two piernas bench (Male)",
  "glute-ham raise": "Elevación glute-ham",
  "gorilla chin": "",
  "groin crunch": "Crunch groin",
  "hack calf raise": "Elevación de pantorrillas hack",
  "hack one leg calf raise": "Elevación de pantorrillas hack una pierna",
  "half knee bends (male)": " (Male)",
  "half sit-up (male)": "Abdominal half (Male)",
  "hamstring stretch": "Estiramiento de isquiotibiales",
  "hands bike": "",
  "hands clasped circular toe touch (male)": "Toque de puntas hands clasped circular (Male)",
  "hands reversed clasped circular toe touch (male)": "Toque de puntas hands reversed clasped circular (Male)",
  "handstand": "",
  "handstand push-up": "Flexión de pino",
  "hanging leg hip raise": "Elevación de cadera colgado pierna",
  "hanging leg raise": "Elevación de piernas colgado",
  "hanging oblique knee raise": "Elevación de rodillas colgado oblicuos",
  "hanging pike": "",
  "hanging straight leg hip raise": "Elevación de cadera colgado recto pierna",
  "hanging straight leg raise": "Elevación de piernas colgado recto",
  "hanging straight twisting leg hip raise": "Elevación de cadera colgado recto con giro pierna",
  "high knee against wall": "",
  "hip raise (bent knee)": "Elevación de cadera (Flexionado knee)",
  "hug keens to chest": "",
  "hyght dumbbell fly": "Apertura hyght dumbbell",
  "hyperextension": "Hiperextensión",
  "hyperextension (on bench)": "Hiperextensión",
  "impossible dips": "Fondos impossible",
  "inchworm": "Oruga",
  "inchworm v. 2": "",
  "incline close-grip push-up": "Flexión inclinado agarre cerrado",
  "incline leg hip raise (leg straight)": "Elevación de cadera inclinado pierna (Pierna recto)",
  "incline push up depth jump": "Empuje inclinado up depth jump",
  "incline push-up": "Flexión inclinada",
  "incline push-up (on box)": "Flexión inclinada",
  "incline reverse grip push-up": "Flexión inclinada agarre inverso",
  "incline scapula push up": "Empuje inclinado scapula up",
  "incline twisting sit-up": "Abdominal inclinado con giro",
  "intermediate hip flexor and quad stretch": "Estiramiento intermediate cadera flexor quad",
  "inverse leg curl (bench support)": "Curl de piernas inverse (Bench support)",
  "inverse leg curl (on pull-up cable machine)": "Curl de piernas inverse (Dominada cable machine)",
  "inverted row": "Remo invertido",
  "inverted row bent knees": "Remo inverted flexionado knees",
  "inverted row on bench": "Remo inverted bench",
  "inverted row v. 2": "Remo inverted v. 2",
  "inverted row with straps": "Remo inverted straps",
  "iron cross stretch": "Estiramiento iron cross",
  "isometric chest squeeze": "",
  "isometric wipers": "",
  "jack burpee": "",
  "jack jump (male)": " (Male)",
  "jackknife sit-up": "Navaja abdominal",
  "janda sit-up": "Abdominal janda",
  "jump rope": "Salto de cuerda",
  "jump squat": "Sentadilla jump",
  "jump squat v. 2": "Sentadilla jump v. 2",
  "kettlebell advanced windmill": " con kettlebell",
  "kettlebell alternating hang clean": "Cargada alterno hang con kettlebell",
  "kettlebell alternating press": "Press alterno con kettlebell",
  "kettlebell alternating press on floor": "Press alterno floor con kettlebell",
  "kettlebell alternating renegade row": "Remo alterno renegade con kettlebell",
  "kettlebell alternating row": "Remo alterno con kettlebell",
  "kettlebell arnold press": "Press arnold con kettlebell",
  "kettlebell bent press": "Press flexionado con kettlebell",
  "kettlebell bottoms up clean from the hang position": "Cargada bottoms up hang position con kettlebell",
  "kettlebell double alternating hang clean": "Cargada doble alterno hang con kettlebell",
  "kettlebell double jerk": " con kettlebell",
  "kettlebell double push press": "Press doble empuje con kettlebell",
  "kettlebell double snatch": "Arranque doble con kettlebell",
  "kettlebell double windmill": " con kettlebell",
  "kettlebell extended range one arm press on floor": "Press extended range un brazo floor con kettlebell",
  "kettlebell figure 8": " con kettlebell",
  "kettlebell front squat": "Sentadilla frontal con kettlebell",
  "kettlebell goblet squat": "Sentadilla goblet con kettlebell",
  "kettlebell hang clean": "Cargada hang con kettlebell",
  "kettlebell lunge pass through": "Zancada pass through con kettlebell",
  "kettlebell one arm clean and jerk": "Cargada un brazo jerk con kettlebell",
  "kettlebell one arm floor press": "Press un brazo floor con kettlebell",
  "kettlebell one arm jerk": " con kettlebell",
  "kettlebell one arm military press to the side": "Press un brazo military lateral con kettlebell",
  "kettlebell one arm push press": "Press un brazo empuje con kettlebell",
  "kettlebell one arm row": "Remo un brazo con kettlebell",
  "kettlebell one arm snatch": "Arranque un brazo con kettlebell",
  "kettlebell pirate supper legs": " con kettlebell",
  "kettlebell pistol squat": "Sentadilla pistol con kettlebell",
  "kettlebell plyo push-up": "Flexión explosiva con kettlebell",
  "kettlebell seated press": "Press sentado con kettlebell",
  "kettlebell seated two arm military press": "Press sentado two brazo military con kettlebell",
  "kettlebell seesaw press": "Press seesaw con kettlebell",
  "kettlebell sumo high pull": "Jalón sumo alta con kettlebell",
  "kettlebell swing": "Balanceo de kettlebell",
  "kettlebell thruster": "Thruster con kettlebell",
  "kettlebell turkish get up (squat style)": " con kettlebell (Sentadilla style)",
  "kettlebell two arm clean": "Cargada two brazo con kettlebell",
  "kettlebell two arm military press": "Press two brazo military con kettlebell",
  "kettlebell two arm row": "Remo two brazo con kettlebell",
  "kettlebell windmill": " con kettlebell",
  "kick out sit": "",
  "kipping muscle up": "",
  "knee touch crunch": "Crunch knee touch",
  "kneeling jump squat": "Sentadilla de rodillas jump",
  "kneeling lat stretch": "Estiramiento de rodillas dorsal",
  "kneeling plank tap shoulder (male)": "Plancha de rodillas tap hombro (Male)",
  "kneeling push-up (male)": "Flexión de rodillas (Male)",
  "korean dips": "Fondos korean",
  "l-pull-up": "",
  "l-sit on floor": "",
  "landmine 180": "",
  "landmine lateral raise": "Elevación landmine lateral",
  "lean planche": "",
  "left hook. boxing": "",
  "leg pull in flat bench": "Jalón pierna flat bench",
  "leg up hamstring stretch": "Estiramiento de isquiotibiales pierna up",
  "lever alternate leg press": "Prensa de piernas alterno con palanca",
  "lever alternating narrow grip seated row": " con palanca",
  "lever assisted chin-up": " con palanca",
  "lever back extension": "Extensión de espalda con palanca",
  "lever bent over row": "Remo inclinado con palanca",
  "lever bent-over row with v-bar": "Remo inclinado v-bar con palanca",
  "lever bicep curl": "Curl bicep con palanca",
  "lever calf press": "Press pantorrilla con palanca",
  "lever chest press": "Press pecho con palanca",
  "lever deadlift": "Peso muerto con palanca",
  "lever decline chest press": "Press declinado pecho con palanca",
  "lever donkey calf raise": "Elevación de pantorrillas donkey con palanca",
  "lever front pulldown": "Jalón frontal con palanca",
  "lever gripless shrug": " con palanca",
  "lever gripless shrug v. 2": " con palanca",
  "lever gripper hands": " con palanca",
  "lever hammer grip preacher curl": "Curl hammer grip preacher con palanca",
  "lever high row": "Remo alta con palanca",
  "lever hip extension v. 2": "Extensión de cadera v. 2 con palanca",
  "lever horizontal one leg press": "Prensa de piernas horizontal one con palanca",
  "lever incline chest press": "Press inclinado pecho con palanca",
  "lever incline chest press v. 2": "Press de pecho inclinado en palanca",
  "lever kneeling leg curl": "Curl de piernas de rodillas con palanca",
  "lever kneeling twist": "Giro de rodillas con palanca",
  "lever lateral raise": "Elevación lateral con palanca",
  "lever leg extension": "Extensión de piernas con palanca",
  "lever lying leg curl": "Curl de piernas acostado con palanca",
  "lever lying two-one leg curl": "Curl de piernas acostado two-one con palanca",
  "lever military press": "Press military con palanca",
  "lever narrow grip seated row": " con palanca",
  "lever one arm bent over row": "Remo inclinado un brazo con palanca",
  "lever one arm lateral high row": "Remo un brazo lateral alta con palanca",
  "lever one arm lateral wide pulldown": "Jalón un brazo lateral amplio con palanca",
  "lever one arm shoulder press": "Press de hombros un brazo con palanca",
  "lever overhand triceps dip": "Fondo de tríceps agarre prono con palanca",
  "lever preacher curl": "Curl preacher con palanca",
  "lever preacher curl v. 2": "Curl preacher v. 2 con palanca",
  "lever pullover": " con palanca",
  "lever reverse grip lateral pulldown": "Jalón agarre inverso lateral con palanca",
  "lever reverse grip preacher curl": "Curl agarre inverso preacher con palanca",
  "lever reverse grip vertical row": "Remo agarre inverso vertical con palanca",
  "lever reverse hyperextension": " con palanca",
  "lever reverse t-bar row": "Remo invertido en T con palanca",
  "lever rotary calf": " con palanca",
  "lever seated calf press": "Press sentado pantorrilla con palanca",
  "lever seated calf raise": "Elevación de pantorrillas sentado con palanca",
  "lever seated crunch": "Crunch sentado con palanca",
  "lever seated crunch (chest pad)": "Crunch sentado con palanca (Pecho pad)",
  "lever seated crunch v. 2": "Crunch sentado v. 2 con palanca",
  "lever seated dip": "Fondo sentado con palanca",
  "lever seated fly": "Apertura sentado con palanca",
  "lever seated good morning": " con palanca",
  "lever seated hip abduction": "Abducción de cadera sentado con palanca",
  "lever seated hip adduction": "Adducción de cadera sentado con palanca",
  "lever seated leg curl": "Curl de piernas sentado con palanca",
  "lever seated leg raise crunch": "Elevación de piernas sentado crunch con palanca",
  "lever seated reverse fly": "Apertura sentado invertido con palanca",
  "lever seated reverse fly (parallel grip)": "Apertura sentado invertido con palanca (Parallel grip)",
  "lever seated row": "Remo sentado con palanca",
  "lever seated squat calf raise on leg press machine": "Elevación de pantorrillas sentado sentadilla pierna press machine con palanca",
  "lever shoulder press": "Press de hombros con palanca",
  "lever shoulder press v. 2": "Press de hombros v. 2 con palanca",
  "lever shoulder press v. 3": "Press de hombros v. 3 con palanca",
  "lever shrug": " con palanca",
  "lever standing calf raise": "Elevación de pantorrillas de pie con palanca",
  "lever standing chest press": "Press de pie pecho con palanca",
  "lever t bar row": "Remo t bar con palanca",
  "lever t-bar reverse grip row": "Remo en T agarre inverso con palanca",
  "lever triceps extension": "Extensión de tríceps con palanca",
  "lever unilateral row": "Remo unilateral con palanca",
  "london bridge": "Puente london",
  "low glute bridge on floor": "Puente de glúteos en el suelo",
  "lower back curl": "Curl inferior espalda",
  "lunge with jump": "Zancada jump",
  "lunge with twist": "Zancada giro",
  "lying (side) quads stretch": "Estiramiento de cuádriceps acostado (Lateral)",
  "lying elbow to knee": "",
  "lying leg raise flat bench": "Elevación de piernas acostado flat bench",
  "lying leg-hip raise": "Elevación acostado leg-hip",
  "machine inner chest press": "Press inner pecho con máquina",
  "march sit (wall)": " (Wall)",
  "medicine ball catch and overhead throw": " con balón medicinal",
  "medicine ball chest pass": " con balón medicinal",
  "medicine ball chest push from 3 point stance": "Empuje pecho 3 point stance con balón medicinal",
  "medicine ball chest push multiple response": "Empuje pecho multiple response con balón medicinal",
  "medicine ball chest push single response": "Empuje pecho una response con balón medicinal",
  "medicine ball chest push with run release": "Empuje pecho run release con balón medicinal",
  "medicine ball close grip push up": "Empuje agarre cerrado up con balón medicinal",
  "medicine ball overhead slam": " con balón medicinal",
  "medicine ball supine chest throw": " con balón medicinal",
  "mixed grip chin-up": "",
  "modified hindu push-up (male)": "Flexión modificado hindu (Male)",
  "modified push up to lower arms": "Empuje modificado up inferior brazos",
  "monster walk": "",
  "mountain climber": "Escalador",
  "muscle up": "",
  "muscle-up (on vertical bar)": "Muscle-up",
  "narrow push-up on exercise ball": "Flexión narrow exercise ball",
  "neck side stretch": "Estiramiento cuello lateral",
  "negative crunch": "Crunch negative",
  "oblique crunch v. 2": "Crunch oblicuos v. 2",
  "oblique crunches floor": "Crunches oblicuos floor",
  "olympic barbell hammer curl": "Curl olympic barbell hammer",
  "olympic barbell triceps extension": "Extensión de tríceps olympic barbell",
  "one arm against wall": "",
  "one arm chin-up": "",
  "one arm dip": "Fondo un brazo",
  "one arm slam (with medicine ball)": " (Medicine ball)",
  "one arm towel row": "Remo un brazo towel",
  "one leg donkey calf raise": "Elevación de pantorrillas una pierna donkey",
  "one leg floor calf raise": "Elevación de pantorrillas una pierna floor",
  "one leg squat": "Sentadilla una pierna",
  "otis up": "",
  "outside leg kick push-up": "Flexión outside pierna kick",
  "overhead triceps stretch": "Estiramiento de tríceps sobre la cabeza",
  "pelvic tilt": "",
  "pelvic tilt into bridge": "Puente pelvic tilt",
  "peroneals stretch": "Estiramiento peroneals",
  "pike-to-cobra push-up": "Flexión pike-to-cobra",
  "plyo push up": "Empuje explosiva up",
  "posterior step to overhead reach": "",
  "posterior tibialis stretch": "Estiramiento de tibial posterior",
  "potty squat": "Sentadilla potty",
  "potty squat with support": "Sentadilla potty support",
  "power clean": "Cargada power",
  "power point plank": "Plancha power point",
  "prisoner half sit-up (male)": "Abdominal prisoner half (Male)",
  "prone twist on stability ball": "Giro boca abajo stability ball",
  "pull up (neutral grip)": "Jalón up (Agarre neutro grip)",
  "pull-in (on stability ball)": "Jalón (Stability ball)",
  "pull-up": "Dominada",
  "push and pull bodyweight": "Jalón empuje bodyweight",
  "push to run": "Empuje run",
  "push up on bosu ball": "Empuje up bosu ball",
  "push-up": "Flexión",
  "push-up (bosu ball)": "Flexión",
  "push-up (on stability ball)": "Flexión",
  "push-up (wall)": "Flexión",
  "push-up (wall) v. 2": "Flexión v. 2 (Wall)",
  "push-up close-grip off dumbbell": "Flexión agarre cerrado off dumbbell",
  "push-up inside leg kick": "Flexión inside pierna kick",
  "push-up medicine ball": "Flexión medicine ball",
  "push-up on lower arms": "Flexión inferior brazos",
  "push-up plus": "Flexión plus",
  "push-up to side plank": "Flexión lateral plancha",
  "quads": "",
  "quarter sit-up": "Abdominal quarter",
  "quick feet v. 2": "",
  "raise single arm push-up": "Flexión elevación una brazo",
  "rear decline bridge": "Puente rear declinado",
  "rear deltoid stretch": "Estiramiento de deltoides rear",
  "rear pull-up": "Dominada rear",
  "reclining big toe pose with rope": "",
  "resistance band hip thrusts on knees (female)": "Empuje de cadera de rodillas con banda",
  "resistance band leg extension": "Extensión de piernas de resistencia band",
  "resistance band seated biceps curl": "Curl de bíceps de resistencia band sentado",
  "resistance band seated chest press": "Press de resistencia band sentado pecho",
  "resistance band seated hip abduction": "Abducción de cadera de resistencia band sentado",
  "resistance band seated shoulder press": "Press de hombros de resistencia band sentado",
  "resistance band seated straight back row": "Remo de resistencia band sentado recto espalda",
  "reverse crunch": "Crunch invertido",
  "reverse dip": "Fondo invertido",
  "reverse grip machine lat pulldown": "Jalón de dorsales agarre inverso machine",
  "reverse grip pull-up": "Dominada agarre inverso",
  "reverse hyper extension (on stability ball)": "Extensión invertido hyper (Stability ball)",
  "reverse hyper on flat bench": "",
  "reverse plank with leg lift": "Plancha invertido pierna lift",
  "ring dips": "Fondos ring",
  "rocking frog stretch": "Estiramiento rocking frog",
  "rocky pull-up pulldown": "Jalón rocky dominada",
  "roller back stretch": "Estiramiento de espalda con rodillo",
  "roller body saw": " con rodillo",
  "roller hip lat stretch": "Estiramiento cadera dorsal con rodillo",
  "roller hip stretch": "Estiramiento cadera con rodillo",
  "roller reverse crunch": "Crunch invertido con rodillo",
  "roller seated shoulder flexor depresor retractor": " con rodillo",
  "roller seated single leg shoulder flexor depresor retractor": " con rodillo",
  "roller side lat stretch": "Estiramiento lateral dorsal con rodillo",
  "rope climb": " con soga",
  "run": "",
  "run (equipment)": " (Equipment)",
  "runners stretch": "Estiramiento runners",
  "russian twist": "Giro ruso",
  "scapula dips": "Fondos scapula",
  "scapula push-up": "Flexión scapula",
  "scapular pull-up": "Dominada scapular",
  "scissor jumps (male)": " (Male)",
  "seated calf stretch (male)": "Estiramiento sentado pantorrilla (Male)",
  "seated glute stretch": "Estiramiento sentado glúteo",
  "seated leg raise": "Elevación de piernas sentado",
  "seated lower back stretch": "Estiramiento de espalda sentado inferior",
  "seated piriformis stretch": "Estiramiento de piriforme sentado",
  "seated side crunch (wall)": "Crunch sentado lateral (Wall)",
  "seated wide angle pose sequence": "",
  "self assisted inverse leg curl": "Curl de piernas self asistido inverse",
  "self assisted inverse leg curl (on floor)": "Curl de piernas self asistido inverse (Floor)",
  "semi squat jump (male)": "Sentadilla semi jump (Male)",
  "short stride run": "",
  "shoulder grip pull-up": "Dominada hombro grip",
  "shoulder tap": "",
  "shoulder tap push-up": "Flexión hombro tap",
  "side bridge hip abduction": "Abducción de cadera lateral puente",
  "side bridge v. 2": "Puente lateral v. 2",
  "side hip (on parallel bars)": " (Parallel bars)",
  "side hip abduction": "Abducción de cadera lateral",
  "side lying floor stretch": "Estiramiento lateral acostado floor",
  "side lying hip adduction (male)": "Adducción de cadera lateral acostado (Male)",
  "side plank hip adduction": "Adducción de cadera lateral plancha",
  "side push neck stretch": "Estiramiento de cuello lateral empuje",
  "side push-up": "Flexión lateral",
  "side wrist pull stretch": "Estiramiento lateral muñeca jalón",
  "side-to-side chin": "",
  "side-to-side toe touch (male)": "Toque de puntas side-to-side (Male)",
  "single arm push-up": "Flexión una brazo",
  "single leg bridge with outstretched leg": "Puente una pierna outstretched pierna",
  "single leg calf raise (on a dumbbell)": "Elevación de pantorrillas una pierna (Dumbbell)",
  "single leg platform slide": "",
  "single leg squat (pistol) male": "Sentadilla una pierna male (Pistol)",
  "sissy squat": "Sentadilla sissy",
  "sit-up v. 2": "Abdominal",
  "sit-up with arms on chest": "Abdominal brazos pecho",
  "skater hops": "",
  "ski ergometer": "",
  "ski step": "",
  "skin the cat": "",
  "sled 45 degrees one leg press": "Prensa de piernas 45 degrees one con trineo",
  "sled 45в° calf press": "Press 45в° pantorrilla con trineo",
  "sled 45в° leg press": "Prensa de piernas 45в° con trineo",
  "sled 45в° leg press (back pov)": "Prensa de piernas 45в° con trineo (Espalda pov)",
  "sled 45° leg press (side pov)": "Prensa de piernas 45° con trineo (Lateral pov)",
  "sled 45в° leg wide press": "Press 45в° pierna amplio con trineo",
  "sled calf press on leg press": "Prensa de piernas pantorrilla press con trineo",
  "sled closer hack squat": "Sentadilla closer hack con trineo",
  "sled forward angled calf raise": "Elevación de pantorrillas forward angled con trineo",
  "sled hack squat": "Sentadilla hack con trineo",
  "sled lying calf press": "Press acostado pantorrilla con trineo",
  "sled lying squat": "Sentadilla acostado con trineo",
  "sled one leg calf press on leg press": "Prensa de piernas una pierna pantorrilla press con trineo",
  "sledge hammer": "",
  "smith back shrug": "",
  "smith behind neck press": "Press smith por detrás cuello",
  "smith bench press": "Press de banca smith",
  "smith bent knee good morning": "",
  "smith bent over row": "Remo inclinado smith",
  "smith chair squat": "Sentadilla smith chair",
  "smith close-grip bench press": "Press de banca smith agarre cerrado",
  "smith deadlift": "Peso muerto smith",
  "smith decline bench press": "Press de banca smith declinado",
  "smith decline reverse-grip press": "Press smith declinado agarre inverso",
  "smith front squat (clean grip)": "Sentadilla smith frontal (Cargada grip)",
  "smith full squat": "Sentadilla smith completa",
  "smith hack squat": "Sentadilla smith hack",
  "smith hip raise": "Elevación de cadera smith",
  "smith incline bench press": "Press de banca smith inclinado",
  "smith incline reverse-grip press": "Press smith inclinado agarre inverso",
  "smith incline shoulder raises": "Elevaciones de hombros smith inclinado",
  "smith leg press": "Prensa de piernas smith",
  "smith low bar squat": "Sentadilla smith bajo bar",
  "smith machine bicep curl": "Curl bicep con máquina Smith",
  "smith machine decline close grip bench press": "Press de banca declinado agarre cerrado con máquina Smith",
  "smith machine incline tricep extension": "Extensión de tríceps inclinado con máquina Smith",
  "smith machine reverse decline close grip bench press": "Press de banca invertido declinado agarre cerrado con máquina Smith",
  "smith narrow row": "",
  "smith one arm row": "Remo smith un brazo",
  "smith one leg floor calf raise": "Elevación de pantorrillas smith una pierna floor",
  "smith rear delt row": "Remo smith rear delt",
  "smith reverse calf raises": "Elevaciones de pantorrillas smith invertido",
  "smith reverse grip bent over row": "Remo inclinado smith agarre inverso",
  "smith reverse-grip press": "Press agarre inverso en Smith",
  "smith seated one leg calf raise": "Elevación de pantorrillas smith sentado una pierna",
  "smith seated shoulder press": "Press de hombros smith sentado",
  "smith seated wrist curl": "Curl de muñeca smith sentado",
  "smith shoulder press": "Press de hombros smith",
  "smith shrug": "",
  "smith single leg split squat": "Sentadilla smith una pierna búlgara",
  "smith sprint lunge": "Zancada smith sprint",
  "smith squat": "Sentadilla smith",
  "smith standing back wrist curl": "Curl de muñeca smith de pie espalda",
  "smith standing behind head military press": "Press smith de pie por detrás head military",
  "smith standing leg calf raise": "Elevación de pantorrillas smith de pie pierna",
  "smith standing military press": "Press smith de pie military",
  "smith sumo squat": "Sentadilla smith sumo",
  "smith toe raise": "Elevación smith toe",
  "smith upright row": "Remo smith upright",
  "smith wide grip bench press": "Press de banca smith agarre amplio",
  "smith wide grip decline bench press": "Press de banca smith agarre amplio declinado",
  "snatch pull": "Arranque jalón",
  "spell caster": "",
  "sphinx": "",
  "spider crawl push up": "Empuje spider crawl up",
  "spine stretch": "Estiramiento spine",
  "spine twist": "Giro spine",
  "split squats": "Sentadillas búlgara",
  "squat jerk": "Sentadilla jerk",
  "squat on bosu ball": "Sentadilla bosu ball",
  "squat to overhead reach": "Sentadilla sobre la cabeza reach",
  "squat to overhead reach with twist": "Sentadilla sobre la cabeza reach giro",
  "stability ball crunch (full range hands behind head)": "Crunch con balón suizo (Completa range hands por detrás head)",
  "stalder press": "Press stalder",
  "standing archer": "",
  "standing behind neck press": "Press de pie por detrás cuello",
  "standing calf raise (on a staircase)": "Elevación de pantorrillas de pie",
  "standing calves": "",
  "standing calves calf stretch": "Estiramiento de pie pantorrillas pantorrilla",
  "standing hamstring and calf stretch with strap": "Estiramiento de pie isquiotibial pantorrilla strap",
  "standing lateral stretch": "Estiramiento de pie lateral",
  "standing pelvic tilt": "",
  "standing single leg curl": "Curl de piernas de pie una",
  "standing wheel rollerout": "",
  "star jump (male)": " (Male)",
  "stationary bike run v. 3": "",
  "stationary bike walk": "",
  "straddle maltese": "",
  "straddle planche": "",
  "straight leg outer hip abductor": "",
  "superman push-up": "Flexión superman",
  "suspended abdominal fallout": "",
  "suspended push-up": "Flexión suspended",
  "suspended reverse crunch": "Crunch invertido suspendido",
  "suspended row": "Remo suspended",
  "suspended split squat": "Sentadilla suspended búlgara",
  "swimmer kicks v. 2 (male)": " (Male)",
  "swing 360": "Balanceo 360",
  "three bench dip": "Fondo three bench",
  "tire flip": " con llanta",
  "trap bar deadlift": "Peso muerto con barra trampa",
  "triceps dip": "Fondo de tríceps",
  "triceps dip (bench leg)": "Fondo de tríceps",
  "triceps dip (between benches)": "Fondo de tríceps",
  "triceps dips floor": "Fondos tríceps floor",
  "triceps press": "Press tríceps",
  "triceps stretch": "Estiramiento de tríceps",
  "tuck crunch": "Crunch tuck",
  "twin handle parallel grip lat pulldown": "Jalón de dorsales twin handle parallel grip",
  "twist hip lift": "Giro cadera lift",
  "twisted leg raise": "Elevación de piernas twisted",
  "twisted leg raise (female)": "Elevación de piernas twisted (Female)",
  "two toe touch (male)": "Toque de puntas two (Male)",
  "upper back stretch": "Estiramiento de espalda superior",
  "upward facing dog": "",
  "v-sit on floor": "",
  "vertical leg raise (on parallel bars)": "Elevación de piernas vertical (Parallel bars)",
  "walk elliptical cross trainer": "",
  "walking high knees lunge": "Zancada walking alta knees",
  "walking lunge": "Zancada caminando",
  "walking on incline treadmill": "",
  "walking on stepmill": "",
  "weighted bench dip": "Fondo bench con peso",
  "weighted close grip chin-up on dip cage": "Fondo agarre cerrado chin-up cage con peso",
  "weighted cossack squats (male)": "Sentadillas cossack con peso (Male)",
  "weighted crunch": "Crunch con peso",
  "weighted decline sit-up": "Abdominal declinado con peso",
  "weighted donkey calf raise": "Elevación de pantorrillas donkey con peso",
  "weighted drop push up": "Empuje drop up con peso",
  "weighted front plank": "Plancha frontal con peso",
  "weighted front raise": "Elevación frontal con peso",
  "weighted hanging leg-hip raise": "Elevación colgado leg-hip con peso",
  "weighted hyperextension (on stability ball)": " con peso (Stability ball)",
  "weighted kneeling step with swing": "Balanceo de rodillas step con peso",
  "weighted lunge with swing": "Zancada balanceo con peso",
  "weighted muscle up": " con peso",
  "weighted muscle up (on bar)": " con peso (Bar)",
  "weighted one hand pull up": "Jalón one hand up con peso",
  "weighted overhead crunch (on stability ball)": "Crunch sobre la cabeza con peso (Stability ball)",
  "weighted pull-up": "Dominada con peso",
  "weighted round arm": " con peso",
  "weighted russian twist": "Giro ruso con peso",
  "weighted russian twist (legs up)": "Giro ruso con peso",
  "weighted russian twist v. 2": "Giro ruso con peso",
  "weighted seated bicep curl (on stability ball)": "Curl sentado bicep con peso (Stability ball)",
  "weighted seated twist (on stability ball)": "Giro sentado con peso (Stability ball)",
  "weighted side bend (on stability ball)": " con peso (Stability ball)",
  "weighted sissy squat": "Sentadilla sissy con peso",
  "weighted squat": "Sentadilla con peso",
  "weighted standing curl": "Curl de pie con peso",
  "weighted standing hand squeeze": " con peso",
  "weighted straight bar dip": "Fondo recto bar con peso",
  "weighted stretch lunge": "Estiramiento zancada con peso",
  "weighted svend press": "Press svend con peso",
  "weighted three bench dips": "Fondos three bench con peso",
  "weighted tricep dips": "Fondos tríceps con peso",
  "weighted triceps dip on high parallel bars": "Fondo de tríceps alta parallel bars con peso",
  "wheel rollerout": " con rueda",
  "wheel run": " con rueda",
  "wide grip pull-up": "Dominada agarre amplio",
  "wide grip rear pull-up": "Dominada agarre amplio rear",
  "wide hand push up": "Empuje amplio hand up",
  "wide-grip chest dip on high parallel bars": "Fondo de pecho agarre amplio alta parallel bars",
  "wind sprints": "",
  "world greatest stretch": "Estiramiento world greatest",
  "wrist circles": "",
  "wrist rollerer": "",
}
