// Mapa de traducciones de ejercicios al español (generado desde exercises-dataset).
// Traducciones curadas por algoritmo con reordenamiento natural.
export const EXERCISE_NAMES_ES: Record<string, string> = {
  "3/4 sit-up": "3/4 abdominal",
  "45° side bend": "45° lateral bend",
  "air bike": "bicicleta en el aire",
  "all fours squad stretch": "All fours squad estiramiento",
  "alternate heel touchers": "Alterno heel touchers",
  "alternate lateral pulldown": "Alterno lateral jalón",
  "ankle circles": "Tobillo circles",
  "archer pull up": "dominada arquera",
  "archer push up": "flexión arquera",
  "arm slingers hanging bent knee legs": "Brazo slingers colgado flexionado knee piernas",
  "arm slingers hanging straight legs": "Brazo slingers colgado recto piernas",
  "arms apart circular toe touch (male)": "Brazos apart circular toe touch (Male)",
  "arms overhead full sit-up (male)": "Brazos sobre la cabeza full abdominal (Male)",
  "assisted chest dip (kneeling)": "Asistido pecho fondo (Kneeling)",
  "assisted hanging knee raise": "Asistido colgado knee elevación",
  "assisted hanging knee raise with throw down": "Asistido colgado knee elevación throw down",
  "assisted lying calves stretch": "Asistido acostado pantorrillas estiramiento",
  "assisted lying glutes stretch": "Asistido acostado glúteos estiramiento",
  "assisted lying gluteus and piriformis stretch": "Asistido acostado gluteus piriformis estiramiento",
  "assisted lying leg raise with lateral throw down": "Asistido acostado pierna elevación lateral throw down",
  "assisted lying leg raise with throw down": "Asistido acostado pierna elevación throw down",
  "assisted motion russian twist": "Asistido motion russian giro",
  "assisted parallel close grip pull-up": "Asistido parallel agarre cerrado dominada",
  "assisted prone hamstring": "Asistido boca abajo isquiotibial",
  "assisted prone lying quads stretch": "Asistido boca abajo acostado cuádriceps estiramiento",
  "assisted prone rectus femoris stretch": "Asistido boca abajo rectus femoris estiramiento",
  "assisted pull-up": "dominada asistida",
  "assisted seated pectoralis major stretch with stability ball": "Asistido sentado pectoralis major estiramiento stability ball",
  "assisted side lying adductor stretch": "Asistido lateral acostado aductores estiramiento",
  "assisted sit-up": "Asistido abdominal",
  "assisted standing chin-up": "Asistido de pie chin-up",
  "assisted standing pull-up": "Asistido de pie dominada",
  "assisted standing triceps extension (with towel)": "Asistido de pie tríceps extensión (With towel)",
  "assisted triceps dip (kneeling)": "Asistido tríceps fondo (Kneeling)",
  "assisted wide-grip chest dip (kneeling)": "Asistido agarre amplio pecho fondo (Kneeling)",
  "astride jumps (male)": "Astride jumps (Male)",
  "back and forth step": "Espalda forth step",
  "back extension on exercise ball": "Extensión de espalda on exercise ball",
  "back lever": "Espalda lever",
  "back pec stretch": "Espalda pec estiramiento",
  "backward jump": "Backward jump",
  "balance board": "Balance board",
  "band alternating biceps curl": "Alterno bíceps curl con banda elástica",
  "band alternating v-up": "Alterno v-up con banda elástica",
  "band assisted pull-up": "Asistido dominada con banda elástica",
  "band assisted wheel rollerout": "Asistido wheel rollerout con banda elástica",
  "band bench press": "Press de banca con banda elástica",
  "band bent-over hip extension": "Bent-over cadera extensión con banda elástica",
  "band bicycle crunch": "Bicycle crunch con banda elástica",
  "band close-grip pulldown": "Agarre cerrado jalón con banda elástica",
  "band close-grip push-up": "Agarre cerrado flexión con banda elástica",
  "band concentration curl": "Concentration curl con banda elástica",
  "band fixed back close grip pulldown": "Fixed espalda agarre cerrado jalón con banda elástica",
  "band fixed back underhand pulldown": "Fixed espalda agarre supino jalón con banda elástica",
  "band front lateral raise": "Frontal lateral elevación con banda elástica",
  "band front raise": "Frontal elevación con banda elástica",
  "band hip lift": "Cadera lift con banda elástica",
  "band horizontal pallof press": "Horizontal pallof press con banda elástica",
  "band jack knife sit-up": "Jack knife abdominal con banda elástica",
  "band kneeling one arm pulldown": "De rodillas un brazo jalón con banda elástica",
  "band kneeling twisting crunch": "De rodillas con giro crunch con banda elástica",
  "band lying hip internal rotation": "Acostado cadera internal rotación con banda elástica",
  "band lying straight leg raise": "Acostado recto pierna elevación con banda elástica",
  "band one arm overhead biceps curl": "Un brazo sobre la cabeza bíceps curl con banda elástica",
  "band one arm single leg split squat": "Un brazo una pierna split sentadilla con banda elástica",
  "band one arm standing low row": "Un brazo de pie bajo remo con banda elástica",
  "band one arm twisting chest press": "Un brazo con giro pecho press con banda elástica",
  "band one arm twisting seated row": "Un brazo con giro sentado remo con banda elástica",
  "band pull through": "Jalón through con banda elástica",
  "band push sit-up": "Empuje abdominal con banda elástica",
  "band reverse fly": "Invertido apertura con banda elástica",
  "band reverse wrist curl": "Invertido muñeca curl con banda elástica",
  "band seated hip internal rotation": "Sentado cadera internal rotación con banda elástica",
  "band seated twist": "Sentado giro con banda elástica",
  "band shoulder press": "Press de hombros con banda elástica",
  "band shrug": "Shrug con banda elástica",
  "band side triceps extension": "Lateral tríceps extensión con banda elástica",
  "band single leg calf raise": "Una pierna pantorrilla elevación con banda elástica",
  "band single leg reverse calf raise": "Una pierna invertido pantorrilla elevación con banda elástica",
  "band single leg split squat": "Una pierna split sentadilla con banda elástica",
  "band squat": "Sentadilla con banda elástica",
  "band squat row": "Sentadilla remo con banda elástica",
  "band standing crunch": "De pie crunch con banda elástica",
  "band standing rear delt row": "De pie rear delt remo con banda elástica",
  "band standing twisting crunch": "De pie con giro crunch con banda elástica",
  "band step-up": "Subida cajón con banda elástica",
  "band stiff leg deadlift": "Stiff pierna peso muerto con banda elástica",
  "band straight back stiff leg deadlift": "Recto espalda stiff pierna peso muerto con banda elástica",
  "band straight leg deadlift": "Recto pierna peso muerto con banda elástica",
  "band twisting overhead press": "Con giro sobre la cabeza press con banda elástica",
  "band two legs calf raise - (band under both legs) v. 2": "Two piernas pantorrilla elevación - v. 2 con banda elástica (Band under both legs)",
  "band underhand pulldown": "Agarre supino jalón con banda elástica",
  "band v-up": "V-up con banda elástica",
  "band vertical pallof press": "Vertical pallof press con banda elástica",
  "band wrist curl": "Curl de muñeca con banda elástica",
  "band y-raise": "Y-raise con banda elástica",
  "barbell alternate biceps curl": "Alterno bíceps curl con barra",
  "barbell bench front squat": "Bench frontal sentadilla con barra",
  "barbell bench press": "Press de banca con barra",
  "barbell bench squat": "Bench sentadilla con barra",
  "barbell bent arm pullover": "Flexionado brazo pullover con barra",
  "barbell bent over row": "remo con barra",
  "barbell biceps curl (with arm blaster)": "Curl de bíceps con barra (With arm blaster)",
  "barbell clean and press": "Cargada press con barra",
  "barbell clean-grip front squat": "Clean-grip frontal sentadilla con barra",
  "barbell close-grip bench press": "Agarre cerrado press de banca con barra",
  "barbell curl": "curl con barra",
  "barbell deadlift": "Peso muerto con barra",
  "barbell decline bench press": "Declinado press de banca con barra",
  "barbell decline bent arm pullover": "Declinado flexionado brazo pullover con barra",
  "barbell decline close grip to skull press": "Declinado agarre cerrado skull press con barra",
  "barbell decline pullover": "Declinado pullover con barra",
  "barbell decline wide-grip press": "Declinado agarre amplio press con barra",
  "barbell decline wide-grip pullover": "Declinado agarre amplio pullover con barra",
  "barbell drag curl": "Drag curl con barra",
  "barbell floor calf raise": "Floor pantorrilla elevación con barra",
  "barbell front chest squat": "Frontal pecho sentadilla con barra",
  "barbell front raise": "Frontal elevación con barra",
  "barbell front raise and pullover": "Frontal elevación pullover con barra",
  "barbell front squat": "Frontal sentadilla con barra",
  "barbell full squat": "Full sentadilla con barra",
  "barbell full squat (back pov)": "Full sentadilla con barra (Back pov)",
  "barbell full squat (side pov)": "Full sentadilla con barra (Side pov)",
  "barbell full zercher squat": "Full zercher sentadilla con barra",
  "barbell glute bridge": "Puente de glúteos con barra",
  "barbell glute bridge two legs on bench (male)": "Puente de glúteos two piernas bench con barra (Male)",
  "barbell good morning": "Good morning con barra",
  "barbell guillotine bench press": "Guillotine press de banca con barra",
  "barbell hack squat": "Hack sentadilla con barra",
  "barbell high bar squat": "Alta bar sentadilla con barra",
  "barbell incline bench press": "Inclinado press de banca con barra",
  "barbell incline close grip bench press": "Inclinado agarre cerrado press de banca con barra",
  "barbell incline reverse-grip press": "Inclinado agarre inverso press con barra",
  "barbell incline row": "Inclinado remo con barra",
  "barbell incline shoulder raise": "Inclinado hombro elevación con barra",
  "barbell jefferson squat": "Jefferson sentadilla con barra",
  "barbell jm bench press": "Jm press de banca con barra",
  "barbell jump squat": "Jump sentadilla con barra",
  "barbell lateral lunge": "Lateral zancada con barra",
  "barbell low bar squat": "Bajo bar sentadilla con barra",
  "barbell lunge": "Zancada con barra",
  "barbell lying back of the head tricep extension": "Acostado espalda head tríceps extensión con barra",
  "barbell lying close-grip press": "Acostado agarre cerrado press con barra",
  "barbell lying close-grip triceps extension": "Acostado agarre cerrado tríceps extensión con barra",
  "barbell lying extension": "Acostado extensión con barra",
  "barbell lying lifting (on hip)": "Acostado lifting con barra (On hip)",
  "barbell lying preacher curl": "Acostado preacher curl con barra",
  "barbell lying triceps extension": "Acostado tríceps extensión con barra",
  "barbell lying triceps extension skull crusher": "Acostado tríceps extensión skull crusher con barra",
  "barbell narrow stance squat": "Narrow stance sentadilla con barra",
  "barbell one arm bent over row": "Un brazo flexionado over remo con barra",
  "barbell one arm floor press": "Un brazo floor press con barra",
  "barbell one arm side deadlift": "Un brazo lateral peso muerto con barra",
  "barbell one arm snatch": "Un brazo arranque con barra",
  "barbell one leg squat": "Una pierna sentadilla con barra",
  "barbell overhead squat": "Sobre la cabeza sentadilla con barra",
  "barbell palms down wrist curl over a bench": "Palms down muñeca curl over bench con barra",
  "barbell palms up wrist curl over a bench": "Palms up muñeca curl over bench con barra",
  "barbell pendlay row": "Pendlay remo con barra",
  "barbell pin presses": "Pin presses con barra",
  "barbell preacher curl": "Preacher curl con barra",
  "barbell press sit-up": "Press abdominal con barra",
  "barbell prone incline curl": "Boca abajo inclinado curl con barra",
  "barbell pullover": "Pullover con barra",
  "barbell pullover to press": "Pullover press con barra",
  "barbell rack pull": "Rack jalón con barra",
  "barbell rear delt raise": "Rear delt elevación con barra",
  "barbell rear delt row": "Rear delt remo con barra",
  "barbell rear lunge": "Rear zancada con barra",
  "barbell rear lunge v. 2": "Rear zancada v. 2 con barra",
  "barbell revers wrist curl v. 2": "Revers muñeca curl v. 2 con barra",
  "barbell reverse close-grip bench press": "Invertido agarre cerrado press de banca con barra",
  "barbell reverse curl": "Invertido curl con barra",
  "barbell reverse grip bent over row": "Agarre inverso flexionado over remo con barra",
  "barbell reverse grip decline bench press": "Agarre inverso declinado press de banca con barra",
  "barbell reverse grip incline bench press": "Agarre inverso inclinado press de banca con barra",
  "barbell reverse grip incline bench row": "Agarre inverso inclinado bench remo con barra",
  "barbell reverse grip skullcrusher": "Agarre inverso skullcrusher con barra",
  "barbell reverse preacher curl": "Invertido preacher curl con barra",
  "barbell reverse wrist curl": "Invertido muñeca curl con barra",
  "barbell rollerout": "Rollerout con barra",
  "barbell rollerout from bench": "Rollerout bench con barra",
  "barbell romanian deadlift": "Romanian peso muerto con barra",
  "barbell seated behind head military press": "Sentado por detrás head military press con barra",
  "barbell seated bradford rocky press": "Sentado bradford rocky press con barra",
  "barbell seated calf raise": "Sentado pantorrilla elevación con barra",
  "barbell seated close grip behind neck triceps extension": "Sentado agarre cerrado por detrás cuello tríceps extensión con barra",
  "barbell seated close-grip concentration curl": "Sentado agarre cerrado concentration curl con barra",
  "barbell seated good morning": "Sentado good morning con barra",
  "barbell seated overhead press": "Sentado sobre la cabeza press con barra",
  "barbell seated overhead triceps extension": "Sentado sobre la cabeza tríceps extensión con barra",
  "barbell seated twist": "Sentado giro con barra",
  "barbell shrug": "Shrug con barra",
  "barbell side bent v. 2": "Lateral flexionado v. 2 con barra",
  "barbell side split squat": "Lateral split sentadilla con barra",
  "barbell side split squat v. 2": "Lateral split sentadilla v. 2 con barra",
  "barbell single leg deadlift": "Una pierna peso muerto con barra",
  "barbell single leg split squat": "Una pierna split sentadilla con barra",
  "barbell sitted alternate leg raise": "Sitted alterno pierna elevación con barra",
  "barbell sitted alternate leg raise (female)": "Sitted alterno pierna elevación con barra (Female)",
  "barbell skier": "Skier con barra",
  "barbell speed squat": "Speed sentadilla con barra",
  "barbell split squat v. 2": "Split sentadilla v. 2 con barra",
  "barbell squat (on knees)": "Sentadilla con barra (On knees)",
  "barbell squat jump step rear lunge": "Sentadilla jump step rear zancada con barra",
  "barbell standing ab rollerout": "De pie abdominales rollerout con barra",
  "barbell standing back wrist curl": "De pie espalda muñeca curl con barra",
  "barbell standing bradford press": "De pie bradford press con barra",
  "barbell standing calf raise": "De pie pantorrilla elevación con barra",
  "barbell standing close grip curl": "De pie agarre cerrado curl con barra",
  "barbell standing close grip military press": "De pie agarre cerrado military press con barra",
  "barbell standing concentration curl": "De pie concentration curl con barra",
  "barbell standing front raise over head": "De pie frontal elevación over head con barra",
  "barbell standing leg calf raise": "De pie pierna pantorrilla elevación con barra",
  "barbell standing overhead triceps extension": "De pie sobre la cabeza tríceps extensión con barra",
  "barbell standing reverse grip curl": "De pie agarre inverso curl con barra",
  "barbell standing rocking leg calf raise": "De pie rocking pierna pantorrilla elevación con barra",
  "barbell standing twist": "De pie giro con barra",
  "barbell standing wide grip biceps curl": "De pie agarre amplio bíceps curl con barra",
  "barbell standing wide military press": "De pie amplio military press con barra",
  "barbell standing wide-grip curl": "De pie agarre amplio curl con barra",
  "barbell step-up": "Subida cajón con barra",
  "barbell stiff leg good morning": "Stiff pierna good morning con barra",
  "barbell straight leg deadlift": "Recto pierna peso muerto con barra",
  "barbell sumo deadlift": "Sumo peso muerto con barra",
  "barbell thruster": "Thruster con barra",
  "barbell upright row": "Upright remo con barra",
  "barbell upright row v. 2": "Upright remo v. 2 con barra",
  "barbell upright row v. 3": "Upright remo v. 3 con barra",
  "barbell wide bench press": "Amplio press de banca con barra",
  "barbell wide reverse grip bench press": "Amplio agarre inverso press de banca con barra",
  "barbell wide squat": "Amplio sentadilla con barra",
  "barbell wide-grip upright row": "Agarre amplio upright remo con barra",
  "barbell wrist curl": "Curl de muñeca con barra",
  "barbell wrist curl v. 2": "Curl de muñeca v. 2 con barra",
  "barbell zercher squat": "Zercher sentadilla con barra",
  "basic toe touch (male)": "Basic toe touch (Male)",
  "battling ropes": "Battling ropes",
  "bear crawl": "caminata de oso",
  "behind head chest stretch": "Por detrás head pecho estiramiento",
  "bench dip (knees bent)": "Fondo con banco (Knees bent)",
  "bench dip on floor": "Fondo floor con banco",
  "bench hip extension": "Extensión de cadera con banco",
  "bench pull-ups": "Dominadas con banco",
  "bent knee lying twist (male)": "Flexionado knee acostado giro (Male)",
  "biceps leg concentration curl": "Bíceps pierna concentration curl",
  "biceps narrow pull-ups": "Bíceps narrow dominadas",
  "biceps pull-up": "Bíceps dominada",
  "body-up": "Body-up",
  "bodyweight drop jump squat": "Bodyweight drop jump sentadilla",
  "bodyweight incline side plank": "Bodyweight inclinado lateral plancha",
  "bodyweight kneeling triceps extension": "Bodyweight de rodillas tríceps extensión",
  "bodyweight side lying biceps curl": "Bodyweight lateral acostado bíceps curl",
  "bodyweight squatting row": "Bodyweight squatting remo",
  "bodyweight squatting row (with towel)": "Bodyweight squatting remo (With towel)",
  "bodyweight standing calf raise": "Bodyweight de pie pantorrilla elevación",
  "bodyweight standing close-grip one arm row": "Bodyweight de pie agarre cerrado un brazo remo",
  "bodyweight standing close-grip row": "Bodyweight de pie agarre cerrado remo",
  "bodyweight standing one arm row": "Bodyweight de pie un brazo remo",
  "bodyweight standing one arm row (with towel)": "Bodyweight de pie un brazo remo (With towel)",
  "bodyweight standing row": "Bodyweight de pie remo",
  "bodyweight standing row (with towel)": "Bodyweight de pie remo (With towel)",
  "bottoms-up": "Bottoms-up",
  "box jump down with one leg stabilization": "Jump down una pierna stabilization con cajón",
  "bridge - mountain climber (cross body)": "Puente - mountain climber (Cross body)",
  "burpee": "burpee",
  "butt-ups": "Butt-ups",
  "butterfly yoga pose": "Butterfly yoga pose",
  "cable alternate shoulder press": "Alterno hombro press con polea",
  "cable alternate triceps extension": "Alterno tríceps extensión con polea",
  "cable assisted inverse leg curl": "Asistido inverse pierna curl con polea",
  "cable bar lateral pulldown": "Bar lateral jalón con polea",
  "cable bench press": "Press de banca con polea",
  "cable close grip curl": "Agarre cerrado curl con polea",
  "cable concentration curl": "Concentration curl con polea",
  "cable concentration extension (on knee)": "Concentration extensión con polea (On knee)",
  "cable cross-over lateral pulldown": "Cross-over lateral jalón con polea",
  "cable cross-over revers fly": "Cross-over revers apertura con polea",
  "cable cross-over variation": "Cross-over variation con polea",
  "cable curl": "Curl con polea",
  "cable deadlift": "Peso muerto con polea",
  "cable decline fly": "Declinado apertura con polea",
  "cable decline one arm press": "Declinado un brazo press con polea",
  "cable decline press": "Declinado press con polea",
  "cable decline seated wide-grip row": "Declinado sentado agarre amplio remo con polea",
  "cable drag curl": "Drag curl con polea",
  "cable floor seated wide-grip row": "Floor sentado agarre amplio remo con polea",
  "cable forward raise": "Forward elevación con polea",
  "cable front raise": "elevación frontal en polea",
  "cable front shoulder raise": "Frontal hombro elevación con polea",
  "cable hammer curl (with rope)": "Hammer curl con polea (With rope)",
  "cable high pulley overhead tricep extension": "Alta pulley sobre la cabeza tríceps extensión con polea",
  "cable high row (kneeling)": "Alta remo con polea (Kneeling)",
  "cable hip adduction": "adducción de cadera en polea",
  "cable incline bench press": "Inclinado press de banca con polea",
  "cable incline bench row": "Inclinado bench remo con polea",
  "cable incline fly": "Inclinado apertura con polea",
  "cable incline fly (on stability ball)": "Inclinado apertura con polea (On stability ball)",
  "cable incline pushdown": "Inclinado pushdown con polea",
  "cable incline triceps extension": "Inclinado tríceps extensión con polea",
  "cable judo flip": "Judo flip con polea",
  "cable kickback": "Patada con polea",
  "cable kneeling crunch": "De rodillas crunch con polea",
  "cable kneeling rear delt row (with rope) (male)": "De rodillas rear delt remo con polea (With rope, Male)",
  "cable kneeling triceps extension": "De rodillas tríceps extensión con polea",
  "cable lat pulldown full range of motion": "Jalón de dorsales full range motion con polea",
  "cable lateral pulldown (with rope attachment)": "Lateral jalón con polea (With rope attachment)",
  "cable lateral pulldown with v-bar": "Lateral jalón v-bar con polea",
  "cable lateral raise": "elevación lateral en polea",
  "cable low fly": "Bajo apertura con polea",
  "cable low seated row": "Bajo sentado remo con polea",
  "cable lying bicep curl": "Acostado bicep curl con polea",
  "cable lying close-grip curl": "Acostado agarre cerrado curl con polea",
  "cable lying extension pullover (with rope attachment)": "Acostado extensión pullover con polea (With rope attachment)",
  "cable lying fly": "Acostado apertura con polea",
  "cable lying triceps extension v. 2": "Acostado tríceps extensión v. 2 con polea",
  "cable middle fly": "Middle apertura con polea",
  "cable one arm bent over row": "Un brazo flexionado over remo con polea",
  "cable one arm curl": "Un brazo curl con polea",
  "cable one arm decline chest fly": "Un brazo declinado pecho apertura con polea",
  "cable one arm fly on exercise ball": "Un brazo apertura exercise ball con polea",
  "cable one arm incline fly on exercise ball": "Un brazo inclinado apertura exercise ball con polea",
  "cable one arm incline press": "Un brazo inclinado press con polea",
  "cable one arm incline press on exercise ball": "Un brazo inclinado press exercise ball con polea",
  "cable one arm lateral bent-over": "Un brazo lateral bent-over con polea",
  "cable one arm lateral raise": "Un brazo lateral elevación con polea",
  "cable one arm preacher curl": "Un brazo preacher curl con polea",
  "cable one arm press on exercise ball": "Un brazo press exercise ball con polea",
  "cable one arm pulldown": "Un brazo jalón con polea",
  "cable one arm reverse preacher curl": "Un brazo invertido preacher curl con polea",
  "cable one arm straight back high row (kneeling)": "Un brazo recto espalda alta remo con polea (Kneeling)",
  "cable one arm tricep pushdown": "Un brazo tríceps pushdown con polea",
  "cable overhead curl": "Sobre la cabeza curl con polea",
  "cable overhead curl on exercise ball": "Sobre la cabeza curl exercise ball con polea",
  "cable overhead triceps extension (rope attachment)": "Sobre la cabeza tríceps extensión con polea (Rope attachment)",
  "cable palm rotational row": "Palm rotational remo con polea",
  "cable preacher curl": "Preacher curl con polea",
  "cable press on exercise ball": "Press exercise ball con polea",
  "cable pull through (with rope)": "Jalón through con polea (With rope)",
  "cable pulldown": "jalón en polea",
  "cable pulldown (pro lat bar)": "Jalón con polea (Pro lat bar)",
  "cable pulldown bicep curl": "Jalón bicep curl con polea",
  "cable pushdown": "Pushdown con polea",
  "cable pushdown (straight arm) v. 2": "Pushdown v. 2 con polea (Straight arm)",
  "cable pushdown (with rope attachment)": "Pushdown con polea (With rope attachment)",
  "cable rear delt row (stirrups)": "Rear delt remo con polea (Stirrups)",
  "cable rear delt row (with rope)": "Rear delt remo con polea (With rope)",
  "cable rear drive": "Rear drive con polea",
  "cable rear pulldown": "Rear jalón con polea",
  "cable reverse crunch": "Invertido crunch con polea",
  "cable reverse curl": "Invertido curl con polea",
  "cable reverse grip triceps pushdown (sz-bar) (with arm blaster)": "Agarre inverso tríceps pushdown con polea (Sz-bar, With arm blaster)",
  "cable reverse one arm curl": "Invertido un brazo curl con polea",
  "cable reverse preacher curl": "Invertido preacher curl con polea",
  "cable reverse wrist curl": "Invertido muñeca curl con polea",
  "cable reverse-grip pushdown": "Agarre inverso pushdown con polea",
  "cable reverse-grip straight back seated high row": "Agarre inverso recto espalda sentado alta remo con polea",
  "cable rope crossover seated row": "Rope crossover sentado remo con polea",
  "cable rope elevated seated row": "Rope elevated sentado remo con polea",
  "cable rope extension incline bench row": "Rope extensión inclinado bench remo con polea",
  "cable rope hammer preacher curl": "Rope hammer preacher curl con polea",
  "cable rope high pulley overhead tricep extension": "Rope alta pulley sobre la cabeza tríceps extensión con polea",
  "cable rope incline tricep extension": "Rope inclinado tríceps extensión con polea",
  "cable rope lying on floor tricep extension": "Rope acostado floor tríceps extensión con polea",
  "cable rope one arm hammer preacher curl": "Rope un brazo hammer preacher curl con polea",
  "cable rope seated row": "Rope sentado remo con polea",
  "cable russian twists (on stability ball)": "Russian giros con polea (On stability ball)",
  "cable seated chest press": "Sentado pecho press con polea",
  "cable seated crunch": "Sentado crunch con polea",
  "cable seated curl": "Sentado curl con polea",
  "cable seated high row (v-bar)": "Sentado alta remo con polea (V-bar)",
  "cable seated one arm alternate row": "Sentado un brazo alterno remo con polea",
  "cable seated one arm concentration curl": "Sentado un brazo concentration curl con polea",
  "cable seated overhead curl": "Sentado sobre la cabeza curl con polea",
  "cable seated rear lateral raise": "Sentado rear lateral elevación con polea",
  "cable seated row": "Sentado remo con polea",
  "cable seated shoulder internal rotation": "Sentado hombro internal rotación con polea",
  "cable seated twist": "Sentado giro con polea",
  "cable seated wide-grip row": "Sentado agarre amplio remo con polea",
  "cable shoulder press": "Press de hombros con polea",
  "cable shrug": "Shrug con polea",
  "cable side bend": "Lateral bend con polea",
  "cable side bend crunch (bosu ball)": "Lateral bend crunch con polea (Bosu ball)",
  "cable side crunch": "Lateral crunch con polea",
  "cable squat row (with rope attachment)": "Sentadilla remo con polea (With rope attachment)",
  "cable squatting curl": "Squatting curl con polea",
  "cable standing back wrist curl": "De pie espalda muñeca curl con polea",
  "cable standing calf raise": "De pie pantorrilla elevación con polea",
  "cable standing cross-over high reverse fly": "De pie cross-over alta invertido apertura con polea",
  "cable standing crunch": "De pie crunch con polea",
  "cable standing crunch (with rope attachment)": "De pie crunch con polea (With rope attachment)",
  "cable standing fly": "De pie apertura con polea",
  "cable standing hip extension": "De pie cadera extensión con polea",
  "cable standing inner curl": "De pie inner curl con polea",
  "cable standing lift": "De pie lift con polea",
  "cable standing one arm triceps extension": "De pie un brazo tríceps extensión con polea",
  "cable standing one leg calf raise": "De pie una pierna pantorrilla elevación con polea",
  "cable standing pulldown (with rope)": "De pie jalón con polea (With rope)",
  "cable standing rear delt row (with rope)": "De pie rear delt remo con polea (With rope)",
  "cable standing reverse grip one arm overhead tricep extension": "De pie agarre inverso un brazo sobre la cabeza tríceps extensión con polea",
  "cable standing row (v-bar)": "De pie remo con polea (V-bar)",
  "cable standing shoulder external rotation": "De pie hombro external rotación con polea",
  "cable standing twist row (v-bar)": "De pie giro remo con polea (V-bar)",
  "cable standing up straight crossovers": "De pie up recto crossovers con polea",
  "cable straight arm pulldown": "Recto brazo jalón con polea",
  "cable straight arm pulldown (with rope)": "Recto brazo jalón con polea (With rope)",
  "cable straight back seated row": "Recto espalda sentado remo con polea",
  "cable supine reverse fly": "Boca arriba invertido apertura con polea",
  "cable thibaudeau kayak row": "Thibaudeau kayak remo con polea",
  "cable triceps pushdown (v-bar)": "Tríceps pushdown con polea (V-bar)",
  "cable triceps pushdown (v-bar) (with arm blaster)": "Tríceps pushdown con polea (V-bar, With arm blaster)",
  "cable tuck reverse crunch": "Tuck invertido crunch con polea",
  "cable twist": "Giro con polea",
  "cable twist (up-down)": "Giro con polea (Up-down)",
  "cable twisting pull": "Con giro jalón con polea",
  "cable two arm curl on incline bench": "Two brazo curl inclinado bench con polea",
  "cable two arm tricep kickback": "Two brazo tríceps patada con polea",
  "cable underhand pulldown": "Agarre supino jalón con polea",
  "cable upper chest crossovers": "Superior pecho crossovers con polea",
  "cable upper row": "Superior remo con polea",
  "cable upright row": "Upright remo con polea",
  "cable wide grip rear pulldown behind neck": "Agarre amplio rear jalón por detrás cuello con polea",
  "cable wrist curl": "Curl de muñeca con polea",
  "calf push stretch with hands against wall": "Pantorrilla empuje estiramiento hands wall",
  "calf stretch with hands against wall": "Pantorrilla estiramiento hands wall",
  "calf stretch with rope": "Pantorrilla estiramiento rope",
  "cambered bar lying row": "Cambered bar acostado remo",
  "captains chair straight leg raise": "Captains chair recto pierna elevación",
  "chair leg extended stretch": "Chair pierna extended estiramiento",
  "chest and front of shoulder stretch": "Pecho frontal hombro estiramiento",
  "chest dip": "fondo de pecho",
  "chest dip (on dip-pull-up cage)": "Pecho fondo (On dip-pull-up cage)",
  "chest dip on straight bar": "Pecho fondo recto bar",
  "chest stretch with exercise ball": "Estiramiento de pecho with exercise ball",
  "chest tap push-up (male)": "Pecho tap flexión (Male)",
  "chin-up": "dominada supina",
  "chin-ups (narrow parallel grip)": "Chin-ups (Narrow parallel grip)",
  "circles knee stretch": "Circles knee estiramiento",
  "clap push up": "Clap empuje up",
  "clock push-up": "Clock flexión",
  "close grip chin-up": "Agarre cerrado chin-up",
  "close-grip push-up": "Agarre cerrado flexión",
  "close-grip push-up (on knees)": "Agarre cerrado flexión (On knees)",
  "cocoons": "Cocoons",
  "crab twist toe touch": "Crab giro toe touch",
  "cross body crunch": "Cross body crunch",
  "crunch (hands overhead)": "Crunch (Hands overhead)",
  "crunch (on stability ball)": "Crunch (On stability ball)",
  "crunch (on stability ball, arms straight)": "Crunch (On stability ball, arms straight)",
  "crunch floor": "Crunch floor",
  "curl-up": "Curl-up",
  "curtsey squat": "Curtsey sentadilla",
  "cycle cross trainer": "Cycle cross trainer",
  "dead bug": "bicho muerto",
  "decline crunch": "Declinado crunch",
  "decline push-up": "flexión declinada",
  "decline sit-up": "Declinado abdominal",
  "deep push up": "Deep empuje up",
  "diamond push-up": "flexión de diamante",
  "donkey calf raise": "Donkey pantorrilla elevación",
  "drop push up": "Drop empuje up",
  "dumbbell alternate biceps curl": "Alterno bíceps curl con mancuernas",
  "dumbbell alternate biceps curl (with arm blaster)": "Alterno bíceps curl con mancuernas (With arm blaster)",
  "dumbbell alternate hammer preacher curl": "Alterno hammer preacher curl con mancuernas",
  "dumbbell alternate preacher curl": "Alterno preacher curl con mancuernas",
  "dumbbell alternate seated hammer curl": "Alterno sentado hammer curl con mancuernas",
  "dumbbell alternate side press": "Alterno lateral press con mancuernas",
  "dumbbell alternating bicep curl with leg raised on exercise ball": "Alterno bicep curl pierna raised exercise ball con mancuernas",
  "dumbbell alternating seated bicep curl on exercise ball": "Alterno sentado bicep curl exercise ball con mancuernas",
  "dumbbell arnold press": "Arnold press con mancuernas",
  "dumbbell arnold press v. 2": "Arnold press v. 2 con mancuernas",
  "dumbbell around pullover": "Around pullover con mancuernas",
  "dumbbell bench press": "Press de banca con mancuernas",
  "dumbbell bench seated press": "Bench sentado press con mancuernas",
  "dumbbell bench squat": "Bench sentadilla con mancuernas",
  "dumbbell bent over row": "Flexionado over remo con mancuernas",
  "dumbbell bicep curl lunge with bowling motion": "Bicep curl zancada bowling motion con mancuernas",
  "dumbbell bicep curl on exercise ball with leg raised": "Bicep curl exercise ball pierna raised con mancuernas",
  "dumbbell bicep curl with stork stance": "Bicep curl stork stance con mancuernas",
  "dumbbell biceps curl": "Curl de bíceps con mancuernas",
  "dumbbell biceps curl (with arm blaster)": "Curl de bíceps con mancuernas (With arm blaster)",
  "dumbbell biceps curl reverse": "Curl de bíceps invertido con mancuernas",
  "dumbbell biceps curl squat": "Curl de bíceps sentadilla con mancuernas",
  "dumbbell biceps curl v sit on bosu ball": "Curl de bíceps v sit bosu ball con mancuernas",
  "dumbbell burpee": "Burpee con mancuernas",
  "dumbbell clean": "Cargada con mancuernas",
  "dumbbell close grip press": "Agarre cerrado press con mancuernas",
  "dumbbell close-grip press": "Agarre cerrado press con mancuernas",
  "dumbbell concentration curl": "Concentration curl con mancuernas",
  "dumbbell contralateral forward lunge": "Contralateral forward zancada con mancuernas",
  "dumbbell cross body hammer curl": "Cross body hammer curl con mancuernas",
  "dumbbell cross body hammer curl v. 2": "Cross body hammer curl v. 2 con mancuernas",
  "dumbbell cuban press": "Cuban press con mancuernas",
  "dumbbell cuban press v. 2": "Cuban press v. 2 con mancuernas",
  "dumbbell deadlift": "Peso muerto con mancuernas",
  "dumbbell decline bench press": "Declinado press de banca con mancuernas",
  "dumbbell decline fly": "Declinado apertura con mancuernas",
  "dumbbell decline hammer press": "Declinado hammer press con mancuernas",
  "dumbbell decline one arm fly": "Declinado un brazo apertura con mancuernas",
  "dumbbell decline one arm hammer press": "Declinado un brazo hammer press con mancuernas",
  "dumbbell decline shrug": "Declinado shrug con mancuernas",
  "dumbbell decline shrug v. 2": "Declinado shrug v. 2 con mancuernas",
  "dumbbell decline triceps extension": "Declinado tríceps extensión con mancuernas",
  "dumbbell decline twist fly": "Declinado giro apertura con mancuernas",
  "dumbbell finger curls": "Finger curls con mancuernas",
  "dumbbell fly": "Apertura con mancuernas",
  "dumbbell fly on exercise ball": "Apertura exercise ball con mancuernas",
  "dumbbell forward lunge triceps extension": "Forward zancada tríceps extensión con mancuernas",
  "dumbbell front raise": "elevación frontal con mancuernas",
  "dumbbell front raise v. 2": "Frontal elevación v. 2 con mancuernas",
  "dumbbell full can lateral raise": "Full can lateral elevación con mancuernas",
  "dumbbell goblet squat": "Goblet sentadilla con mancuernas",
  "dumbbell hammer curl": "Hammer curl con mancuernas",
  "dumbbell hammer curl on exercise ball": "Hammer curl exercise ball con mancuernas",
  "dumbbell hammer curl v. 2": "Hammer curl v. 2 con mancuernas",
  "dumbbell hammer curls (with arm blaster)": "Hammer curls con mancuernas (With arm blaster)",
  "dumbbell high curl": "Alta curl con mancuernas",
  "dumbbell incline alternate press": "Inclinado alterno press con mancuernas",
  "dumbbell incline bench press": "Inclinado press de banca con mancuernas",
  "dumbbell incline biceps curl": "Inclinado bíceps curl con mancuernas",
  "dumbbell incline breeding": "Inclinado breeding con mancuernas",
  "dumbbell incline curl": "Inclinado curl con mancuernas",
  "dumbbell incline curl v. 2": "Inclinado curl v. 2 con mancuernas",
  "dumbbell incline fly": "Inclinado apertura con mancuernas",
  "dumbbell incline fly on exercise ball": "Inclinado apertura exercise ball con mancuernas",
  "dumbbell incline hammer curl": "Inclinado hammer curl con mancuernas",
  "dumbbell incline hammer press": "Inclinado hammer press con mancuernas",
  "dumbbell incline hammer press on exercise ball": "Inclinado hammer press exercise ball con mancuernas",
  "dumbbell incline inner biceps curl": "Inclinado inner bíceps curl con mancuernas",
  "dumbbell incline one arm fly": "Inclinado un brazo apertura con mancuernas",
  "dumbbell incline one arm fly on exercise ball": "Inclinado un brazo apertura exercise ball con mancuernas",
  "dumbbell incline one arm hammer press": "Inclinado un brazo hammer press con mancuernas",
  "dumbbell incline one arm hammer press on exercise ball": "Inclinado un brazo hammer press exercise ball con mancuernas",
  "dumbbell incline one arm lateral raise": "Inclinado un brazo lateral elevación con mancuernas",
  "dumbbell incline one arm press": "Inclinado un brazo press con mancuernas",
  "dumbbell incline one arm press on exercise ball": "Inclinado un brazo press exercise ball con mancuernas",
  "dumbbell incline palm-in press": "Inclinado palm-in press con mancuernas",
  "dumbbell incline press on exercise ball": "Inclinado press exercise ball con mancuernas",
  "dumbbell incline raise": "Inclinado elevación con mancuernas",
  "dumbbell incline rear lateral raise": "Inclinado rear lateral elevación con mancuernas",
  "dumbbell incline row": "Inclinado remo con mancuernas",
  "dumbbell incline shoulder raise": "Inclinado hombro elevación con mancuernas",
  "dumbbell incline shrug": "Inclinado shrug con mancuernas",
  "dumbbell incline t-raise": "Inclinado t-raise con mancuernas",
  "dumbbell incline triceps extension": "Inclinado tríceps extensión con mancuernas",
  "dumbbell incline twisted flyes": "Inclinado twisted flyes con mancuernas",
  "dumbbell incline two arm extension": "Inclinado two brazo extensión con mancuernas",
  "dumbbell incline y-raise": "Inclinado y-raise con mancuernas",
  "dumbbell iron cross": "Iron cross con mancuernas",
  "dumbbell kickback": "Patada con mancuernas",
  "dumbbell kickbacks on exercise ball": "Patadas exercise ball con mancuernas",
  "dumbbell kneeling bicep curl exercise ball": "De rodillas bicep curl exercise ball con mancuernas",
  "dumbbell lateral raise": "elevación lateral con mancuernas",
  "dumbbell lateral to front raise": "Lateral frontal elevación con mancuernas",
  "dumbbell lunge": "Zancada con mancuernas",
  "dumbbell lunge with bicep curl": "Zancada bicep curl con mancuernas",
  "dumbbell lying extension (across face)": "Acostado extensión con mancuernas (Across face)",
  "dumbbell lying alternate extension": "Acostado alterno extensión con mancuernas",
  "dumbbell lying elbow press": "Acostado elbow press con mancuernas",
  "dumbbell lying external shoulder rotation": "Acostado external hombro rotación con mancuernas",
  "dumbbell lying femoral": "Acostado femoral con mancuernas",
  "dumbbell lying hammer press": "Acostado hammer press con mancuernas",
  "dumbbell lying on floor rear delt raise": "Acostado floor rear delt elevación con mancuernas",
  "dumbbell lying one arm deltoid rear": "Acostado un brazo deltoides rear con mancuernas",
  "dumbbell lying one arm press": "Acostado un brazo press con mancuernas",
  "dumbbell lying one arm press v. 2": "Acostado un brazo press v. 2 con mancuernas",
  "dumbbell lying one arm pronated triceps extension": "Acostado un brazo pronated tríceps extensión con mancuernas",
  "dumbbell lying one arm rear lateral raise": "Acostado un brazo rear lateral elevación con mancuernas",
  "dumbbell lying one arm supinated triceps extension": "Acostado un brazo supinated tríceps extensión con mancuernas",
  "dumbbell lying pronation": "Acostado pronation con mancuernas",
  "dumbbell lying pronation on floor": "Acostado pronation floor con mancuernas",
  "dumbbell lying pullover on exercise ball": "Acostado pullover exercise ball con mancuernas",
  "dumbbell lying rear delt row": "Acostado rear delt remo con mancuernas",
  "dumbbell lying rear lateral raise": "Acostado rear lateral elevación con mancuernas",
  "dumbbell lying single extension": "Acostado una extensión con mancuernas",
  "dumbbell lying supination": "Acostado supination con mancuernas",
  "dumbbell lying supination on floor": "Acostado supination floor con mancuernas",
  "dumbbell lying supine biceps curl": "Acostado boca arriba bíceps curl con mancuernas",
  "dumbbell lying supine curl": "Acostado boca arriba curl con mancuernas",
  "dumbbell lying triceps extension": "Acostado tríceps extensión con mancuernas",
  "dumbbell lying wide curl": "Acostado amplio curl con mancuernas",
  "dumbbell neutral grip bench press": "Agarre neutro grip press de banca con mancuernas",
  "dumbbell one arm bench fly": "Un brazo bench apertura con mancuernas",
  "dumbbell one arm bent-over row": "Un brazo bent-over remo con mancuernas",
  "dumbbell one arm chest fly on exercise ball": "Un brazo pecho apertura exercise ball con mancuernas",
  "dumbbell one arm concentration curl (on stability ball)": "Un brazo concentration curl con mancuernas (On stability ball)",
  "dumbbell one arm decline chest press": "Un brazo declinado pecho press con mancuernas",
  "dumbbell one arm fly on exercise ball": "Un brazo apertura exercise ball con mancuernas",
  "dumbbell one arm french press on exercise ball": "Un brazo french press exercise ball con mancuernas",
  "dumbbell one arm hammer preacher curl": "Un brazo hammer preacher curl con mancuernas",
  "dumbbell one arm hammer press on exercise ball": "Un brazo hammer press exercise ball con mancuernas",
  "dumbbell one arm incline chest press": "Un brazo inclinado pecho press con mancuernas",
  "dumbbell one arm kickback": "Un brazo patada con mancuernas",
  "dumbbell one arm lateral raise": "Un brazo lateral elevación con mancuernas",
  "dumbbell one arm lateral raise with support": "Un brazo lateral elevación support con mancuernas",
  "dumbbell one arm press on exercise ball": "Un brazo press exercise ball con mancuernas",
  "dumbbell one arm prone curl": "Un brazo boca abajo curl con mancuernas",
  "dumbbell one arm prone hammer curl": "Un brazo boca abajo hammer curl con mancuernas",
  "dumbbell one arm pullover on exercise ball": "Un brazo pullover exercise ball con mancuernas",
  "dumbbell one arm reverse wrist curl": "Un brazo invertido muñeca curl con mancuernas",
  "dumbbell one arm reverse fly (with support)": "Un brazo invertido apertura con mancuernas (With support)",
  "dumbbell one arm reverse grip press": "Un brazo agarre inverso press con mancuernas",
  "dumbbell one arm reverse preacher curl": "Un brazo invertido preacher curl con mancuernas",
  "dumbbell one arm reverse spider curl": "Un brazo invertido spider curl con mancuernas",
  "dumbbell one arm seated bicep curl on exercise ball": "Un brazo sentado bicep curl exercise ball con mancuernas",
  "dumbbell one arm seated hammer curl": "Un brazo sentado hammer curl con mancuernas",
  "dumbbell one arm seated neutral wrist curl": "Un brazo sentado agarre neutro muñeca curl con mancuernas",
  "dumbbell one arm shoulder press": "Un brazo hombro press con mancuernas",
  "dumbbell one arm shoulder press v. 2": "Un brazo hombro press v. 2 con mancuernas",
  "dumbbell one arm snatch": "Un brazo arranque con mancuernas",
  "dumbbell one arm standing curl": "Un brazo de pie curl con mancuernas",
  "dumbbell one arm standing hammer curl": "Un brazo de pie hammer curl con mancuernas",
  "dumbbell one arm triceps extension (on bench)": "Un brazo tríceps extensión con mancuernas (On bench)",
  "dumbbell one arm upright row": "Un brazo upright remo con mancuernas",
  "dumbbell one arm wrist curl": "Un brazo muñeca curl con mancuernas",
  "dumbbell one arm zottman preacher curl": "Un brazo zottman preacher curl con mancuernas",
  "dumbbell one leg fly on exercise ball": "Una pierna apertura exercise ball con mancuernas",
  "dumbbell over bench neutral wrist curl": "Over bench agarre neutro muñeca curl con mancuernas",
  "dumbbell over bench one arm neutral wrist curl": "Over bench un brazo agarre neutro muñeca curl con mancuernas",
  "dumbbell over bench one arm reverse wrist curl": "Over bench un brazo invertido muñeca curl con mancuernas",
  "dumbbell over bench one arm wrist curl": "Over bench un brazo muñeca curl con mancuernas",
  "dumbbell over bench revers wrist curl": "Over bench revers muñeca curl con mancuernas",
  "dumbbell over bench wrist curl": "Over bench muñeca curl con mancuernas",
  "dumbbell palm rotational bent over row": "Palm rotational flexionado over remo con mancuernas",
  "dumbbell palms in incline bench press": "Palms inclinado press de banca con mancuernas",
  "dumbbell peacher hammer curl": "Peacher hammer curl con mancuernas",
  "dumbbell plyo squat": "Explosiva sentadilla con mancuernas",
  "dumbbell preacher curl": "Preacher curl con mancuernas",
  "dumbbell preacher curl over exercise ball": "Preacher curl over exercise ball con mancuernas",
  "dumbbell press on exercise ball": "Press exercise ball con mancuernas",
  "dumbbell pronate-grip triceps extension": "Pronate-grip tríceps extensión con mancuernas",
  "dumbbell prone incline curl": "Boca abajo inclinado curl con mancuernas",
  "dumbbell prone incline hammer curl": "Boca abajo inclinado hammer curl con mancuernas",
  "dumbbell pullover": "Pullover con mancuernas",
  "dumbbell pullover hip extension on exercise ball": "Pullover cadera extensión exercise ball con mancuernas",
  "dumbbell pullover on exercise ball": "Pullover exercise ball con mancuernas",
  "dumbbell push press": "Empuje press con mancuernas",
  "dumbbell raise": "Elevación con mancuernas",
  "dumbbell rear delt raise": "Rear delt elevación con mancuernas",
  "dumbbell rear delt row_shoulder": "Rear delt row_shoulder con mancuernas",
  "dumbbell rear fly": "Rear apertura con mancuernas",
  "dumbbell rear lateral raise": "Rear lateral elevación con mancuernas",
  "dumbbell rear lateral raise (support head)": "Rear lateral elevación con mancuernas (Support head)",
  "dumbbell rear lunge": "Rear zancada con mancuernas",
  "dumbbell revers grip biceps curl": "Revers grip bíceps curl con mancuernas",
  "dumbbell reverse bench press": "Invertido press de banca con mancuernas",
  "dumbbell reverse fly": "Invertido apertura con mancuernas",
  "dumbbell reverse grip incline bench one arm row": "Agarre inverso inclinado bench un brazo remo con mancuernas",
  "dumbbell reverse grip incline bench two arm row": "Agarre inverso inclinado bench two brazo remo con mancuernas",
  "dumbbell reverse grip row (female)": "Agarre inverso remo con mancuernas (Female)",
  "dumbbell reverse preacher curl": "Invertido preacher curl con mancuernas",
  "dumbbell reverse spider curl": "Invertido spider curl con mancuernas",
  "dumbbell reverse wrist curl": "Invertido muñeca curl con mancuernas",
  "dumbbell romanian deadlift": "Romanian peso muerto con mancuernas",
  "dumbbell rotation reverse fly": "Rotación invertido apertura con mancuernas",
  "dumbbell scott press": "Scott press con mancuernas",
  "dumbbell seated alternate front raise": "Sentado alterno frontal elevación con mancuernas",
  "dumbbell seated alternate hammer curl on exercise ball": "Sentado alterno hammer curl exercise ball con mancuernas",
  "dumbbell seated alternate press": "Sentado alterno press con mancuernas",
  "dumbbell seated alternate shoulder": "Sentado alterno hombro con mancuernas",
  "dumbbell seated bench extension": "Sentado bench extensión con mancuernas",
  "dumbbell seated bent arm lateral raise": "Sentado flexionado brazo lateral elevación con mancuernas",
  "dumbbell seated bent over alternate kickback": "Sentado flexionado over alterno patada con mancuernas",
  "dumbbell seated bent over triceps extension": "Sentado flexionado over tríceps extensión con mancuernas",
  "dumbbell seated bicep curl": "Sentado bicep curl con mancuernas",
  "dumbbell seated biceps curl (on stability ball)": "Sentado bíceps curl con mancuernas (On stability ball)",
  "dumbbell seated biceps curl to shoulder press": "Sentado bíceps curl hombro press con mancuernas",
  "dumbbell seated calf raise": "Sentado pantorrilla elevación con mancuernas",
  "dumbbell seated curl": "Sentado curl con mancuernas",
  "dumbbell seated front raise": "Sentado frontal elevación con mancuernas",
  "dumbbell seated hammer curl": "Sentado hammer curl con mancuernas",
  "dumbbell seated inner biceps curl": "Sentado inner bíceps curl con mancuernas",
  "dumbbell seated kickback": "Sentado patada con mancuernas",
  "dumbbell seated lateral raise": "Sentado lateral elevación con mancuernas",
  "dumbbell seated lateral raise v. 2": "Sentado lateral elevación v. 2 con mancuernas",
  "dumbbell seated neutral wrist curl": "Sentado agarre neutro muñeca curl con mancuernas",
  "dumbbell seated one arm bicep curl on exercise ball with leg raised": "Sentado un brazo bicep curl exercise ball pierna raised con mancuernas",
  "dumbbell seated one arm kickback": "Sentado un brazo patada con mancuernas",
  "dumbbell seated one arm rotate": "Sentado un brazo rotate con mancuernas",
  "dumbbell seated one leg calf raise": "Sentado una pierna pantorrilla elevación con mancuernas",
  "dumbbell seated one leg calf raise - hammer grip": "Sentado una pierna pantorrilla elevación - hammer grip con mancuernas",
  "dumbbell seated one leg calf raise - palm up": "Sentado una pierna pantorrilla elevación - palm up con mancuernas",
  "dumbbell seated palms up wrist curl": "Sentado palms up muñeca curl con mancuernas",
  "dumbbell seated preacher curl": "Sentado preacher curl con mancuernas",
  "dumbbell seated revers grip concentration curl": "Sentado revers grip concentration curl con mancuernas",
  "dumbbell seated reverse grip one arm overhead tricep extension": "Sentado agarre inverso un brazo sobre la cabeza tríceps extensión con mancuernas",
  "dumbbell seated shoulder press": "Sentado hombro press con mancuernas",
  "dumbbell seated shoulder press (parallel grip)": "Sentado hombro press con mancuernas (Parallel grip)",
  "dumbbell seated triceps extension": "Sentado tríceps extensión con mancuernas",
  "dumbbell shrug": "Shrug con mancuernas",
  "dumbbell side bend": "Lateral bend con mancuernas",
  "dumbbell side lying one hand raise": "Lateral acostado one hand elevación con mancuernas",
  "dumbbell side plank with rear fly": "Lateral plancha rear apertura con mancuernas",
  "dumbbell single arm overhead carry": "Una brazo sobre la cabeza carry con mancuernas",
  "dumbbell single leg calf raise": "Una pierna pantorrilla elevación con mancuernas",
  "dumbbell single leg deadlift": "Una pierna peso muerto con mancuernas",
  "dumbbell single leg deadlift with stepbox support": "Una pierna peso muerto stepbox support con mancuernas",
  "dumbbell single leg split squat": "Una pierna split sentadilla con mancuernas",
  "dumbbell single leg squat": "Una pierna sentadilla con mancuernas",
  "dumbbell squat": "Sentadilla con mancuernas",
  "dumbbell standing alternate hammer curl and press": "De pie alterno hammer curl press con mancuernas",
  "dumbbell standing alternate overhead press": "De pie alterno sobre la cabeza press con mancuernas",
  "dumbbell standing alternate raise": "De pie alterno elevación con mancuernas",
  "dumbbell standing alternating tricep kickback": "De pie alterno tríceps patada con mancuernas",
  "dumbbell standing around world": "De pie around world con mancuernas",
  "dumbbell standing bent over one arm triceps extension": "De pie flexionado over un brazo tríceps extensión con mancuernas",
  "dumbbell standing bent over two arm triceps extension": "De pie flexionado over two brazo tríceps extensión con mancuernas",
  "dumbbell standing biceps curl": "De pie bíceps curl con mancuernas",
  "dumbbell standing calf raise": "De pie pantorrilla elevación con mancuernas",
  "dumbbell standing concentration curl": "De pie concentration curl con mancuernas",
  "dumbbell standing front raise above head": "De pie frontal elevación above head con mancuernas",
  "dumbbell standing inner biceps curl v. 2": "De pie inner bíceps curl v. 2 con mancuernas",
  "dumbbell standing kickback": "De pie patada con mancuernas",
  "dumbbell standing one arm concentration curl": "De pie un brazo concentration curl con mancuernas",
  "dumbbell standing one arm curl (over incline bench)": "De pie un brazo curl con mancuernas (Over incline bench)",
  "dumbbell standing one arm curl over incline bench": "De pie un brazo curl over inclinado bench con mancuernas",
  "dumbbell standing one arm extension": "De pie un brazo extensión con mancuernas",
  "dumbbell standing one arm palm in press": "De pie un brazo palm press con mancuernas",
  "dumbbell standing one arm reverse curl": "De pie un brazo invertido curl con mancuernas",
  "dumbbell standing overhead press": "De pie sobre la cabeza press con mancuernas",
  "dumbbell standing palms in press": "De pie palms press con mancuernas",
  "dumbbell standing preacher curl": "De pie preacher curl con mancuernas",
  "dumbbell standing reverse curl": "De pie invertido curl con mancuernas",
  "dumbbell standing triceps extension": "De pie tríceps extensión con mancuernas",
  "dumbbell standing zottman preacher curl": "De pie zottman preacher curl con mancuernas",
  "dumbbell step up single leg balance with bicep curl": "Step up una pierna balance bicep curl con mancuernas",
  "dumbbell step-up": "Subida cajón con mancuernas",
  "dumbbell step-up lunge": "Subida cajón zancada con mancuernas",
  "dumbbell step-up split squat": "Subida cajón split sentadilla con mancuernas",
  "dumbbell stiff leg deadlift": "Stiff pierna peso muerto con mancuernas",
  "dumbbell straight arm pullover": "Recto brazo pullover con mancuernas",
  "dumbbell straight leg deadlift": "Recto pierna peso muerto con mancuernas",
  "dumbbell sumo pull through": "Sumo jalón through con mancuernas",
  "dumbbell supported squat": "Supported sentadilla con mancuernas",
  "dumbbell tate press": "Tate press con mancuernas",
  "dumbbell tricep kickback with stork stance": "Tríceps patada stork stance con mancuernas",
  "dumbbell twisting bench press": "Con giro press de banca con mancuernas",
  "dumbbell upright row": "Upright remo con mancuernas",
  "dumbbell upright row (back pov)": "Upright remo con mancuernas (Back pov)",
  "dumbbell upright shoulder external rotation": "Upright hombro external rotación con mancuernas",
  "dumbbell waiter biceps curl": "Waiter bíceps curl con mancuernas",
  "dumbbell w-press": "W-press con mancuernas",
  "dumbbell zottman curl": "Zottman curl con mancuernas",
  "dumbbell zottman preacher curl": "Zottman preacher curl con mancuernas",
  "dumbbells seated triceps extension": "Sentado tríceps extensión con mancuernas",
  "dynamic chest stretch (male)": "Dynamic pecho estiramiento (Male)",
  "elbow dips": "Elbow fondos",
  "elbow lift - reverse push-up": "Elbow lift - invertido flexión",
  "elbow-to-knee": "Elbow-to-knee",
  "elevator": "Elevator",
  "exercise ball alternating arm ups": "Alterno brazo ups con balón suizo",
  "exercise ball back extension with arms extended": "Extensión de espalda brazos extended con balón suizo",
  "exercise ball back extension with hands behind head": "Extensión de espalda hands por detrás head con balón suizo",
  "exercise ball back extension with knees off ground": "Extensión de espalda knees off ground con balón suizo",
  "exercise ball back extension with rotation": "Extensión de espalda rotación con balón suizo",
  "exercise ball dip": "Fondo con balón suizo",
  "exercise ball hip flexor stretch": "Cadera flexor estiramiento con balón suizo",
  "exercise ball hug": "Hug con balón suizo",
  "exercise ball lat stretch": "Dorsal estiramiento con balón suizo",
  "exercise ball lower back stretch (pyramid)": "Inferior espalda estiramiento con balón suizo (Pyramid)",
  "exercise ball lying side lat stretch": "Acostado lateral dorsal estiramiento con balón suizo",
  "exercise ball on the wall calf raise": "Wall pantorrilla elevación con balón suizo",
  "exercise ball on the wall calf raise (tennis ball between ankles)": "Wall pantorrilla elevación con balón suizo (Tennis ball between ankles)",
  "exercise ball on the wall calf raise (tennis ball between knees)": "Wall pantorrilla elevación con balón suizo (Tennis ball between knees)",
  "exercise ball one leg prone lower body rotation": "Una pierna boca abajo inferior body rotación con balón suizo",
  "exercise ball one legged diagonal kick hamstring curl": "One legged diagonal kick isquiotibial curl con balón suizo",
  "exercise ball pike push up": "Pike empuje up con balón suizo",
  "exercise ball prone leg raise": "Boca abajo pierna elevación con balón suizo",
  "exercise ball seated hamstring stretch": "Sentado isquiotibial estiramiento con balón suizo",
  "exercise ball seated triceps stretch": "Sentado tríceps estiramiento con balón suizo",
  "exercise ball supine triceps extension": "Boca arriba tríceps extensión con balón suizo",
  "ez bar french press on exercise ball": "Ez bar french press exercise ball",
  "ez bar lying bent arms pullover": "Ez bar acostado flexionado brazos pullover",
  "ez bar lying close grip triceps extension behind head": "Ez bar acostado agarre cerrado tríceps extensión por detrás head",
  "ez bar reverse grip bent over row": "Ez bar agarre inverso flexionado over remo",
  "ez bar seated close grip concentration curl": "Ez bar sentado agarre cerrado concentration curl",
  "ez bar standing french press": "Ez bar de pie french press",
  "ez barbell anti gravity press": "Anti gravity press con barra EZ",
  "ez barbell close grip preacher curl": "Agarre cerrado preacher curl con barra EZ",
  "ez barbell close-grip curl": "Agarre cerrado curl con barra EZ",
  "ez barbell curl": "Curl con barra EZ",
  "ez barbell decline close grip face press": "Declinado agarre cerrado face press con barra EZ",
  "ez barbell decline triceps extension": "Declinado tríceps extensión con barra EZ",
  "ez barbell incline triceps extension": "Inclinado tríceps extensión con barra EZ",
  "ez barbell jm bench press": "Jm press de banca con barra EZ",
  "ez barbell reverse grip curl": "Agarre inverso curl con barra EZ",
  "ez barbell reverse grip preacher curl": "Agarre inverso preacher curl con barra EZ",
  "ez barbell seated curls": "Sentado curls con barra EZ",
  "ez barbell seated triceps extension": "Sentado tríceps extensión con barra EZ",
  "ez barbell spider curl": "Spider curl con barra EZ",
  "ez-bar biceps curl (with arm blaster)": "Curl de bíceps con barra EZ (With arm blaster)",
  "ez-bar close-grip bench press": "Agarre cerrado press de banca con barra EZ",
  "ez-barbell standing wide grip biceps curl": "Ez-barbell de pie agarre amplio bíceps curl",
  "farmers walk": "Farmers walk",
  "finger curls": "Finger curls",
  "flag": "Flag",
  "flexion leg sit up (bent knee)": "Flexion pierna sit up (Bent knee)",
  "flexion leg sit up (straight arm)": "Flexion pierna sit up (Straight arm)",
  "floor fly (with barbell)": "Floor apertura (With barbell)",
  "flutter kicks": "patadas alternas",
  "forward jump": "Forward jump",
  "forward lunge (male)": "Forward zancada (Male)",
  "frankenstein squat": "Frankenstein sentadilla",
  "frog crunch": "Frog crunch",
  "frog planche": "Frog planche",
  "front lever": "Frontal lever",
  "front lever reps": "Frontal lever reps",
  "front plank with twist": "Frontal plancha giro",
  "full maltese": "Full maltese",
  "full planche": "Full planche",
  "full planche push-up": "Full planche flexión",
  "gironda sternum chin": "Gironda sternum chin",
  "glute bridge march": "Puente de glúteos march",
  "glute bridge two legs on bench (male)": "Puente de glúteos two legs on bench (male)",
  "glute-ham raise": "Glute-ham elevación",
  "gorilla chin": "Gorilla chin",
  "groin crunch": "Groin crunch",
  "hack calf raise": "Hack pantorrilla elevación",
  "hack one leg calf raise": "Hack una pierna pantorrilla elevación",
  "half knee bends (male)": "Half knee bends (Male)",
  "half sit-up (male)": "Half abdominal (Male)",
  "hamstring stretch": "Estiramiento de isquiotibiales",
  "hands bike": "Hands bike",
  "hands clasped circular toe touch (male)": "Hands clasped circular toe touch (Male)",
  "hands reversed clasped circular toe touch (male)": "Hands reversed clasped circular toe touch (Male)",
  "handstand": "Handstand",
  "handstand push-up": "flexión de pino",
  "hanging leg hip raise": "Colgado pierna cadera elevación",
  "hanging leg raise": "Colgado pierna elevación",
  "hanging oblique knee raise": "Colgado oblicuos knee elevación",
  "hanging pike": "Colgado pike",
  "hanging straight leg hip raise": "Colgado recto pierna cadera elevación",
  "hanging straight leg raise": "Colgado recto pierna elevación",
  "hanging straight twisting leg hip raise": "Colgado recto con giro pierna cadera elevación",
  "high knee against wall": "Alta knee wall",
  "hip raise (bent knee)": "Elevación de cadera (bent knee)",
  "hug keens to chest": "Hug keens pecho",
  "hyght dumbbell fly": "Hyght dumbbell apertura",
  "hyperextension": "hiperextensión",
  "hyperextension (on bench)": "Hyperextension (On bench)",
  "impossible dips": "Impossible fondos",
  "inchworm": "oruga",
  "inchworm v. 2": "Inchworm v. 2",
  "incline close-grip push-up": "Inclinado agarre cerrado flexión",
  "incline leg hip raise (leg straight)": "Inclinado pierna cadera elevación (Leg straight)",
  "incline push up depth jump": "Inclinado empuje up depth jump",
  "incline push-up": "flexión inclinada",
  "incline push-up (on box)": "Inclinado flexión (On box)",
  "incline reverse grip push-up": "Inclinado agarre inverso flexión",
  "incline scapula push up": "Inclinado scapula empuje up",
  "incline twisting sit-up": "Inclinado con giro abdominal",
  "intermediate hip flexor and quad stretch": "Intermediate cadera flexor quad estiramiento",
  "inverse leg curl (bench support)": "Inverse pierna curl (Bench support)",
  "inverse leg curl (on pull-up cable machine)": "Inverse pierna curl (On pull-up cable machine)",
  "inverted row": "remo invertido",
  "inverted row bent knees": "Inverted remo flexionado knees",
  "inverted row on bench": "Inverted remo bench",
  "inverted row v. 2": "Inverted remo v. 2",
  "inverted row with straps": "Inverted remo straps",
  "iron cross stretch": "Iron cross estiramiento",
  "isometric chest squeeze": "Isométrico pecho squeeze",
  "isometric wipers": "Isométrico wipers",
  "jack burpee": "Jack burpee",
  "jack jump (male)": "Jack jump (Male)",
  "jackknife sit-up": "Navaja abdominal",
  "janda sit-up": "Janda abdominal",
  "jump rope": "salto de cuerda",
  "jump squat": "Jump sentadilla",
  "jump squat v. 2": "Jump sentadilla v. 2",
  "kettlebell advanced windmill": "Advanced windmill con kettlebell",
  "kettlebell alternating hang clean": "Alterno hang cargada con kettlebell",
  "kettlebell alternating press": "Alterno press con kettlebell",
  "kettlebell alternating press on floor": "Alterno press floor con kettlebell",
  "kettlebell alternating renegade row": "Alterno renegade remo con kettlebell",
  "kettlebell alternating row": "Alterno remo con kettlebell",
  "kettlebell arnold press": "Arnold press con kettlebell",
  "kettlebell bent press": "Flexionado press con kettlebell",
  "kettlebell bottoms up clean from the hang position": "Bottoms up cargada hang position con kettlebell",
  "kettlebell double alternating hang clean": "Doble alterno hang cargada con kettlebell",
  "kettlebell double jerk": "Doble jerk con kettlebell",
  "kettlebell double push press": "Doble empuje press con kettlebell",
  "kettlebell double snatch": "Doble arranque con kettlebell",
  "kettlebell double windmill": "Doble windmill con kettlebell",
  "kettlebell extended range one arm press on floor": "Extended range un brazo press floor con kettlebell",
  "kettlebell figure 8": "Figure 8 con kettlebell",
  "kettlebell front squat": "Frontal sentadilla con kettlebell",
  "kettlebell goblet squat": "Goblet sentadilla con kettlebell",
  "kettlebell hang clean": "Hang cargada con kettlebell",
  "kettlebell lunge pass through": "Zancada pass through con kettlebell",
  "kettlebell one arm clean and jerk": "Un brazo cargada jerk con kettlebell",
  "kettlebell one arm floor press": "Un brazo floor press con kettlebell",
  "kettlebell one arm jerk": "Un brazo jerk con kettlebell",
  "kettlebell one arm military press to the side": "Un brazo military press lateral con kettlebell",
  "kettlebell one arm push press": "Un brazo empuje press con kettlebell",
  "kettlebell one arm row": "Un brazo remo con kettlebell",
  "kettlebell one arm snatch": "Un brazo arranque con kettlebell",
  "kettlebell pirate supper legs": "Pirate supper piernas con kettlebell",
  "kettlebell pistol squat": "Pistol sentadilla con kettlebell",
  "kettlebell plyo push-up": "Explosiva flexión con kettlebell",
  "kettlebell seated press": "Sentado press con kettlebell",
  "kettlebell seated two arm military press": "Sentado two brazo military press con kettlebell",
  "kettlebell seesaw press": "Seesaw press con kettlebell",
  "kettlebell sumo high pull": "Sumo alta jalón con kettlebell",
  "kettlebell swing": "balanceo de kettlebell",
  "kettlebell thruster": "Thruster con kettlebell",
  "kettlebell turkish get up (squat style)": "Turco get up con kettlebell (Squat style)",
  "kettlebell two arm clean": "Two brazo cargada con kettlebell",
  "kettlebell two arm military press": "Two brazo military press con kettlebell",
  "kettlebell two arm row": "Two brazo remo con kettlebell",
  "kettlebell windmill": "Windmill con kettlebell",
  "kick out sit": "Kick out sit",
  "kipping muscle up": "Kipping muscle up",
  "knee touch crunch": "Knee touch crunch",
  "kneeling jump squat": "De rodillas jump sentadilla",
  "kneeling lat stretch": "De rodillas dorsal estiramiento",
  "kneeling plank tap shoulder (male)": "De rodillas plancha tap hombro (Male)",
  "kneeling push-up (male)": "De rodillas flexión (Male)",
  "korean dips": "Korean fondos",
  "l-pull-up": "L-pull-up",
  "l-sit on floor": "L-sit floor",
  "landmine 180": "Landmine 180",
  "landmine lateral raise": "Landmine lateral elevación",
  "lean planche": "Lean planche",
  "left hook. boxing": "Left hook. boxing",
  "leg pull in flat bench": "Pierna jalón flat bench",
  "leg up hamstring stretch": "Pierna up isquiotibial estiramiento",
  "lever alternate leg press": "Alterno pierna press con palanca",
  "lever alternating narrow grip seated row": "Alterno narrow grip sentado remo con palanca",
  "lever assisted chin-up": "Asistido chin-up con palanca",
  "lever back extension": "Extensión de espalda con palanca",
  "lever bent over row": "Flexionado over remo con palanca",
  "lever bent-over row with v-bar": "Bent-over remo v-bar con palanca",
  "lever bicep curl": "Bicep curl con palanca",
  "lever calf press": "Pantorrilla press con palanca",
  "lever chest press": "Pecho press con palanca",
  "lever deadlift": "Peso muerto con palanca",
  "lever decline chest press": "Declinado pecho press con palanca",
  "lever donkey calf raise": "Donkey pantorrilla elevación con palanca",
  "lever front pulldown": "Frontal jalón con palanca",
  "lever gripless shrug": "Gripless shrug con palanca",
  "lever gripless shrug v. 2": "Gripless shrug v. 2 con palanca",
  "lever gripper hands": "Gripper hands con palanca",
  "lever hammer grip preacher curl": "Hammer grip preacher curl con palanca",
  "lever high row": "Alta remo con palanca",
  "lever hip extension v. 2": "Extensión de cadera v. 2 con palanca",
  "lever horizontal one leg press": "Horizontal una pierna press con palanca",
  "lever incline chest press": "Inclinado pecho press con palanca",
  "lever incline chest press v. 2": "Inclinado pecho press v. 2 con palanca",
  "lever kneeling leg curl": "De rodillas pierna curl con palanca",
  "lever kneeling twist": "De rodillas giro con palanca",
  "lever lateral raise": "Lateral elevación con palanca",
  "lever leg extension": "Extensión de piernas con palanca",
  "lever lying leg curl": "Acostado pierna curl con palanca",
  "lever lying two-one leg curl": "Acostado two-one pierna curl con palanca",
  "lever military press": "Military press con palanca",
  "lever narrow grip seated row": "Narrow grip sentado remo con palanca",
  "lever one arm bent over row": "Un brazo flexionado over remo con palanca",
  "lever one arm lateral high row": "Un brazo lateral alta remo con palanca",
  "lever one arm lateral wide pulldown": "Un brazo lateral amplio jalón con palanca",
  "lever one arm shoulder press": "Un brazo hombro press con palanca",
  "lever overhand triceps dip": "Agarre prono tríceps fondo con palanca",
  "lever preacher curl": "Preacher curl con palanca",
  "lever preacher curl v. 2": "Preacher curl v. 2 con palanca",
  "lever pullover": "Pullover con palanca",
  "lever reverse grip lateral pulldown": "Agarre inverso lateral jalón con palanca",
  "lever reverse grip preacher curl": "Agarre inverso preacher curl con palanca",
  "lever reverse grip vertical row": "Agarre inverso vertical remo con palanca",
  "lever reverse hyperextension": "Invertido hyperextension con palanca",
  "lever reverse t-bar row": "Invertido en T remo con palanca",
  "lever rotary calf": "Rotary pantorrilla con palanca",
  "lever seated calf press": "Sentado pantorrilla press con palanca",
  "lever seated calf raise": "Sentado pantorrilla elevación con palanca",
  "lever seated crunch": "Sentado crunch con palanca",
  "lever seated crunch (chest pad)": "Sentado crunch con palanca (Chest pad)",
  "lever seated crunch v. 2": "Sentado crunch v. 2 con palanca",
  "lever seated dip": "Sentado fondo con palanca",
  "lever seated fly": "Sentado apertura con palanca",
  "lever seated good morning": "Sentado good morning con palanca",
  "lever seated hip abduction": "Sentado cadera abducción con palanca",
  "lever seated hip adduction": "Sentado cadera adducción con palanca",
  "lever seated leg curl": "Sentado pierna curl con palanca",
  "lever seated leg raise crunch": "Sentado pierna elevación crunch con palanca",
  "lever seated reverse fly": "Sentado invertido apertura con palanca",
  "lever seated reverse fly (parallel grip)": "Sentado invertido apertura con palanca (Parallel grip)",
  "lever seated row": "Sentado remo con palanca",
  "lever seated squat calf raise on leg press machine": "Sentado sentadilla pantorrilla elevación pierna press machine con palanca",
  "lever shoulder press": "Press de hombros con palanca",
  "lever shoulder press v. 2": "Press de hombros v. 2 con palanca",
  "lever shoulder press v. 3": "Press de hombros v. 3 con palanca",
  "lever shrug": "Shrug con palanca",
  "lever standing calf raise": "De pie pantorrilla elevación con palanca",
  "lever standing chest press": "De pie pecho press con palanca",
  "lever t bar row": "T bar remo con palanca",
  "lever t-bar reverse grip row": "En T agarre inverso remo con palanca",
  "lever triceps extension": "Extensión de tríceps con palanca",
  "lever unilateral row": "Unilateral remo con palanca",
  "london bridge": "London puente",
  "low glute bridge on floor": "Bajo glúteo puente floor",
  "lower back curl": "Inferior espalda curl",
  "lunge with jump": "Zancada jump",
  "lunge with twist": "Zancada giro",
  "lying (side) quads stretch": "Acostado cuádriceps estiramiento (Side)",
  "lying elbow to knee": "Acostado elbow knee",
  "lying leg raise flat bench": "Acostado pierna elevación flat bench",
  "lying leg-hip raise": "Acostado leg-hip elevación",
  "machine inner chest press": "Inner pecho press con máquina",
  "march sit (wall)": "March sit (Wall)",
  "medicine ball catch and overhead throw": "Catch sobre la cabeza throw con balón medicinal",
  "medicine ball chest pass": "Pecho pass con balón medicinal",
  "medicine ball chest push from 3 point stance": "Pecho empuje 3 point stance con balón medicinal",
  "medicine ball chest push multiple response": "Pecho empuje multiple response con balón medicinal",
  "medicine ball chest push single response": "Pecho empuje una response con balón medicinal",
  "medicine ball chest push with run release": "Pecho empuje run release con balón medicinal",
  "medicine ball close grip push up": "Agarre cerrado empuje up con balón medicinal",
  "medicine ball overhead slam": "Sobre la cabeza slam con balón medicinal",
  "medicine ball supine chest throw": "Boca arriba pecho throw con balón medicinal",
  "mixed grip chin-up": "Mixed grip chin-up",
  "modified hindu push-up (male)": "Modificado hindu flexión (Male)",
  "modified push up to lower arms": "Modificado empuje up inferior brazos",
  "monster walk": "Monster walk",
  "mountain climber": "escalador",
  "muscle up": "Muscle up",
  "muscle-up (on vertical bar)": "Muscle-up (On vertical bar)",
  "narrow push-up on exercise ball": "Narrow flexión exercise ball",
  "neck side stretch": "Cuello lateral estiramiento",
  "negative crunch": "Negative crunch",
  "oblique crunch v. 2": "Oblicuos crunch v. 2",
  "oblique crunches floor": "Oblicuos crunches floor",
  "olympic barbell hammer curl": "Olympic barbell hammer curl",
  "olympic barbell triceps extension": "Olympic barbell tríceps extensión",
  "one arm against wall": "Un brazo wall",
  "one arm chin-up": "Un brazo chin-up",
  "one arm dip": "Un brazo fondo",
  "one arm slam (with medicine ball)": "Un brazo slam (With medicine ball)",
  "one arm towel row": "Un brazo towel remo",
  "one leg donkey calf raise": "Una pierna donkey pantorrilla elevación",
  "one leg floor calf raise": "Una pierna floor pantorrilla elevación",
  "one leg squat": "Una pierna sentadilla",
  "otis up": "Otis up",
  "outside leg kick push-up": "Outside pierna kick flexión",
  "overhead triceps stretch": "Sobre la cabeza tríceps estiramiento",
  "pelvic tilt": "Pelvic tilt",
  "pelvic tilt into bridge": "Pelvic tilt puente",
  "peroneals stretch": "Peroneals estiramiento",
  "pike-to-cobra push-up": "Pike-to-cobra flexión",
  "plyo push up": "Explosiva empuje up",
  "posterior step to overhead reach": "Posterior step sobre la cabeza reach",
  "posterior tibialis stretch": "Posterior tibialis estiramiento",
  "potty squat": "Potty sentadilla",
  "potty squat with support": "Potty sentadilla support",
  "power clean": "Power cargada",
  "power point plank": "Power point plancha",
  "prisoner half sit-up (male)": "Prisoner half abdominal (Male)",
  "prone twist on stability ball": "Boca abajo giro stability ball",
  "pull up (neutral grip)": "Jalón up (Neutral grip)",
  "pull-in (on stability ball)": "Pull-in (On stability ball)",
  "pull-up": "dominada",
  "push and pull bodyweight": "Empuje jalón bodyweight",
  "push to run": "Empuje run",
  "push up on bosu ball": "Empuje up bosu ball",
  "push-up": "flexión",
  "push-up (bosu ball)": "Flexión (Bosu ball)",
  "push-up (on stability ball)": "Flexión (On stability ball)",
  "push-up (wall)": "Flexión (Wall)",
  "push-up (wall) v. 2": "Flexión v. 2 (Wall)",
  "push-up close-grip off dumbbell": "Flexión agarre cerrado off dumbbell",
  "push-up inside leg kick": "Flexión inside pierna kick",
  "push-up medicine ball": "Flexión medicine ball",
  "push-up on lower arms": "Flexión inferior brazos",
  "push-up plus": "Flexión plus",
  "push-up to side plank": "Flexión lateral plancha",
  "quads": "Cuádriceps",
  "quarter sit-up": "Quarter abdominal",
  "quick feet v. 2": "Quick feet v. 2",
  "raise single arm push-up": "Elevación una brazo flexión",
  "rear decline bridge": "Rear declinado puente",
  "rear deltoid stretch": "Rear deltoides estiramiento",
  "rear pull-up": "Rear dominada",
  "reclining big toe pose with rope": "Reclining big toe pose rope",
  "resistance band hip thrusts on knees (female)": "De resistencia band cadera empujes knees (Female)",
  "resistance band leg extension": "De resistencia band pierna extensión",
  "resistance band seated biceps curl": "De resistencia band sentado bíceps curl",
  "resistance band seated chest press": "De resistencia band sentado pecho press",
  "resistance band seated hip abduction": "De resistencia band sentado cadera abducción",
  "resistance band seated shoulder press": "De resistencia band sentado hombro press",
  "resistance band seated straight back row": "De resistencia band sentado recto espalda remo",
  "reverse crunch": "Invertido crunch",
  "reverse dip": "Invertido fondo",
  "reverse grip machine lat pulldown": "Agarre inverso machine dorsal jalón",
  "reverse grip pull-up": "Agarre inverso dominada",
  "reverse hyper extension (on stability ball)": "Invertido hyper extensión (On stability ball)",
  "reverse hyper on flat bench": "Invertido hyper flat bench",
  "reverse plank with leg lift": "Invertido plancha pierna lift",
  "ring dips": "Ring fondos",
  "rocking frog stretch": "Rocking frog estiramiento",
  "rocky pull-up pulldown": "Rocky dominada jalón",
  "roller back stretch": "Estiramiento de espalda con rodillo",
  "roller body saw": "Body saw con rodillo",
  "roller hip lat stretch": "Cadera dorsal estiramiento con rodillo",
  "roller hip stretch": "Cadera estiramiento con rodillo",
  "roller reverse crunch": "Invertido crunch con rodillo",
  "roller seated shoulder flexor depresor retractor": "Sentado hombro flexor depresor retractor con rodillo",
  "roller seated single leg shoulder flexor depresor retractor": "Sentado una pierna hombro flexor depresor retractor con rodillo",
  "roller side lat stretch": "Lateral dorsal estiramiento con rodillo",
  "rope climb": "Climb con soga",
  "run": "Run",
  "run (equipment)": "Run (Equipment)",
  "runners stretch": "Runners estiramiento",
  "russian twist": "giro ruso",
  "scapula dips": "Scapula fondos",
  "scapula push-up": "Scapula flexión",
  "scapular pull-up": "Scapular dominada",
  "scissor jumps (male)": "Scissor jumps (Male)",
  "seated calf stretch (male)": "Sentado pantorrilla estiramiento (Male)",
  "seated glute stretch": "Sentado glúteo estiramiento",
  "seated leg raise": "Sentado pierna elevación",
  "seated lower back stretch": "Sentado inferior espalda estiramiento",
  "seated piriformis stretch": "Sentado piriformis estiramiento",
  "seated side crunch (wall)": "Sentado lateral crunch (Wall)",
  "seated wide angle pose sequence": "Sentado amplio angle pose sequence",
  "self assisted inverse leg curl": "Self asistido inverse pierna curl",
  "self assisted inverse leg curl (on floor)": "Self asistido inverse pierna curl (On floor)",
  "semi squat jump (male)": "Semi sentadilla jump (Male)",
  "short stride run": "Short stride run",
  "shoulder grip pull-up": "Hombro grip dominada",
  "shoulder tap": "Hombro tap",
  "shoulder tap push-up": "Hombro tap flexión",
  "side bridge hip abduction": "Lateral puente cadera abducción",
  "side bridge v. 2": "Lateral puente v. 2",
  "side hip (on parallel bars)": "Lateral cadera (On parallel bars)",
  "side hip abduction": "Lateral cadera abducción",
  "side lying floor stretch": "Lateral acostado floor estiramiento",
  "side lying hip adduction (male)": "Lateral acostado cadera adducción (Male)",
  "side plank hip adduction": "Lateral plancha cadera adducción",
  "side push neck stretch": "Lateral empuje cuello estiramiento",
  "side push-up": "Lateral flexión",
  "side wrist pull stretch": "Lateral muñeca jalón estiramiento",
  "side-to-side chin": "Side-to-side chin",
  "side-to-side toe touch (male)": "Side-to-side toe touch (Male)",
  "single arm push-up": "Una brazo flexión",
  "single leg bridge with outstretched leg": "Una pierna puente outstretched pierna",
  "single leg calf raise (on a dumbbell)": "Una pierna pantorrilla elevación (On a dumbbell)",
  "single leg platform slide": "Una pierna platform slide",
  "single leg squat (pistol) male": "Una pierna sentadilla male (Pistol)",
  "sissy squat": "sentadilla sissy",
  "sit-up v. 2": "Abdominal v. 2",
  "sit-up with arms on chest": "Abdominal brazos pecho",
  "skater hops": "Skater hops",
  "ski ergometer": "Ski ergometer",
  "ski step": "Ski step",
  "skin the cat": "Skin cat",
  "sled 45 degrees one leg press": "45 degrees una pierna press con trineo",
  "sled 45в° calf press": "45в° pantorrilla press con trineo",
  "sled 45в° leg press": "45в° pierna press con trineo",
  "sled 45в° leg press (back pov)": "45в° pierna press con trineo (Back pov)",
  "sled 45° leg press (side pov)": "45° pierna press con trineo (Side pov)",
  "sled 45в° leg wide press": "45в° pierna amplio press con trineo",
  "sled calf press on leg press": "Pantorrilla press pierna press con trineo",
  "sled closer hack squat": "Closer hack sentadilla con trineo",
  "sled forward angled calf raise": "Forward angled pantorrilla elevación con trineo",
  "sled hack squat": "Hack sentadilla con trineo",
  "sled lying calf press": "Acostado pantorrilla press con trineo",
  "sled lying squat": "Acostado sentadilla con trineo",
  "sled one leg calf press on leg press": "Una pierna pantorrilla press pierna press con trineo",
  "sledge hammer": "Sledge hammer",
  "smith back shrug": "Smith espalda shrug",
  "smith behind neck press": "Smith por detrás cuello press",
  "smith bench press": "Smith press de banca",
  "smith bent knee good morning": "Smith flexionado knee good morning",
  "smith bent over row": "Smith flexionado over remo",
  "smith chair squat": "Smith chair sentadilla",
  "smith close-grip bench press": "Smith agarre cerrado press de banca",
  "smith deadlift": "Smith peso muerto",
  "smith decline bench press": "Smith declinado press de banca",
  "smith decline reverse-grip press": "Smith declinado agarre inverso press",
  "smith front squat (clean grip)": "Smith frontal sentadilla (Clean grip)",
  "smith full squat": "Smith full sentadilla",
  "smith hack squat": "Smith hack sentadilla",
  "smith hip raise": "Smith cadera elevación",
  "smith incline bench press": "Smith inclinado press de banca",
  "smith incline reverse-grip press": "Smith inclinado agarre inverso press",
  "smith incline shoulder raises": "Smith inclinado hombro elevaciones",
  "smith leg press": "Smith pierna press",
  "smith low bar squat": "Smith bajo bar sentadilla",
  "smith machine bicep curl": "Bicep curl con máquina Smith",
  "smith machine decline close grip bench press": "Declinado agarre cerrado press de banca con máquina Smith",
  "smith machine incline tricep extension": "Inclinado tríceps extensión con máquina Smith",
  "smith machine reverse decline close grip bench press": "Invertido declinado agarre cerrado press de banca con máquina Smith",
  "smith narrow row": "Smith narrow remo",
  "smith one arm row": "Smith un brazo remo",
  "smith one leg floor calf raise": "Smith una pierna floor pantorrilla elevación",
  "smith rear delt row": "Smith rear delt remo",
  "smith reverse calf raises": "Smith invertido pantorrilla elevaciones",
  "smith reverse grip bent over row": "Smith agarre inverso flexionado over remo",
  "smith reverse-grip press": "Smith agarre inverso press",
  "smith seated one leg calf raise": "Smith sentado una pierna pantorrilla elevación",
  "smith seated shoulder press": "Smith sentado hombro press",
  "smith seated wrist curl": "Smith sentado muñeca curl",
  "smith shoulder press": "Smith hombro press",
  "smith shrug": "Smith shrug",
  "smith single leg split squat": "Smith una pierna split sentadilla",
  "smith sprint lunge": "Smith sprint zancada",
  "smith squat": "Smith sentadilla",
  "smith standing back wrist curl": "Smith de pie espalda muñeca curl",
  "smith standing behind head military press": "Smith de pie por detrás head military press",
  "smith standing leg calf raise": "Smith de pie pierna pantorrilla elevación",
  "smith standing military press": "Smith de pie military press",
  "smith sumo squat": "Smith sumo sentadilla",
  "smith toe raise": "Smith toe elevación",
  "smith upright row": "Smith upright remo",
  "smith wide grip bench press": "Smith agarre amplio press de banca",
  "smith wide grip decline bench press": "Smith agarre amplio declinado press de banca",
  "snatch pull": "Arranque jalón",
  "spell caster": "Spell caster",
  "sphinx": "Sphinx",
  "spider crawl push up": "Spider crawl empuje up",
  "spine stretch": "Spine estiramiento",
  "spine twist": "Spine giro",
  "split squats": "Split sentadillas",
  "squat jerk": "Sentadilla jerk",
  "squat on bosu ball": "Sentadilla bosu ball",
  "squat to overhead reach": "Sentadilla sobre la cabeza reach",
  "squat to overhead reach with twist": "Sentadilla sobre la cabeza reach giro",
  "stability ball crunch (full range hands behind head)": "Crunch con balón suizo (Full range hands behind head)",
  "stalder press": "Stalder press",
  "standing archer": "De pie archer",
  "standing behind neck press": "De pie por detrás cuello press",
  "standing calf raise (on a staircase)": "De pie pantorrilla elevación (On a staircase)",
  "standing calves": "De pie pantorrillas",
  "standing calves calf stretch": "De pie pantorrillas pantorrilla estiramiento",
  "standing hamstring and calf stretch with strap": "De pie isquiotibial pantorrilla estiramiento strap",
  "standing lateral stretch": "De pie lateral estiramiento",
  "standing pelvic tilt": "De pie pelvic tilt",
  "standing single leg curl": "De pie una pierna curl",
  "standing wheel rollerout": "De pie wheel rollerout",
  "star jump (male)": "Star jump (Male)",
  "stationary bike run v. 3": "Stationary bike run v. 3",
  "stationary bike walk": "Stationary bike walk",
  "straddle maltese": "Straddle maltese",
  "straddle planche": "Straddle planche",
  "straight leg outer hip abductor": "Recto pierna outer cadera abductores",
  "superman push-up": "Superman flexión",
  "suspended abdominal fallout": "Suspended abdominal fallout",
  "suspended push-up": "Suspended flexión",
  "suspended reverse crunch": "Suspended invertido crunch",
  "suspended row": "Suspended remo",
  "suspended split squat": "Suspended split sentadilla",
  "swimmer kicks v. 2 (male)": "Swimmer kicks v. 2 (Male)",
  "swing 360": "Balanceo 360",
  "three bench dip": "Three bench fondo",
  "tire flip": "Flip con llanta",
  "trap bar deadlift": "peso muerto con barra trampa",
  "triceps dip": "fondo de tríceps",
  "triceps dip (bench leg)": "Tríceps fondo (Bench leg)",
  "triceps dip (between benches)": "Tríceps fondo (Between benches)",
  "triceps dips floor": "Tríceps fondos floor",
  "triceps press": "Tríceps press",
  "triceps stretch": "Tríceps estiramiento",
  "tuck crunch": "Tuck crunch",
  "twin handle parallel grip lat pulldown": "Twin handle parallel grip dorsal jalón",
  "twist hip lift": "Giro cadera lift",
  "twisted leg raise": "Twisted pierna elevación",
  "twisted leg raise (female)": "Twisted pierna elevación (Female)",
  "two toe touch (male)": "Two toe touch (Male)",
  "upper back stretch": "Superior espalda estiramiento",
  "upward facing dog": "Upward facing dog",
  "v-sit on floor": "V-sit floor",
  "vertical leg raise (on parallel bars)": "Vertical pierna elevación (On parallel bars)",
  "walk elliptical cross trainer": "Walk elliptical cross trainer",
  "walking high knees lunge": "Walking alta knees zancada",
  "walking lunge": "zancada caminando",
  "walking on incline treadmill": "Walking inclinado treadmill",
  "walking on stepmill": "Walking stepmill",
  "weighted bench dip": "Bench fondo con peso",
  "weighted close grip chin-up on dip cage": "Agarre cerrado chin-up fondo cage con peso",
  "weighted cossack squats (male)": "Cossack sentadillas con peso (Male)",
  "weighted crunch": "Crunch con peso",
  "weighted decline sit-up": "Declinado abdominal con peso",
  "weighted donkey calf raise": "Donkey pantorrilla elevación con peso",
  "weighted drop push up": "Drop empuje up con peso",
  "weighted front plank": "Frontal plancha con peso",
  "weighted front raise": "Frontal elevación con peso",
  "weighted hanging leg-hip raise": "Colgado leg-hip elevación con peso",
  "weighted hyperextension (on stability ball)": "Hyperextension con peso (On stability ball)",
  "weighted kneeling step with swing": "De rodillas step balanceo con peso",
  "weighted lunge with swing": "Zancada balanceo con peso",
  "weighted muscle up": "Muscle up con peso",
  "weighted muscle up (on bar)": "Muscle up con peso (On bar)",
  "weighted one hand pull up": "One hand jalón up con peso",
  "weighted overhead crunch (on stability ball)": "Sobre la cabeza crunch con peso (On stability ball)",
  "weighted pull-up": "dominada con peso",
  "weighted round arm": "Round brazo con peso",
  "weighted russian twist": "Russian giro con peso",
  "weighted russian twist (legs up)": "Russian giro con peso (Legs up)",
  "weighted russian twist v. 2": "Russian giro v. 2 con peso",
  "weighted seated bicep curl (on stability ball)": "Sentado bicep curl con peso (On stability ball)",
  "weighted seated twist (on stability ball)": "Sentado giro con peso (On stability ball)",
  "weighted side bend (on stability ball)": "Lateral bend con peso (On stability ball)",
  "weighted sissy squat": "Sissy sentadilla con peso",
  "weighted squat": "Sentadilla con peso",
  "weighted standing curl": "De pie curl con peso",
  "weighted standing hand squeeze": "De pie hand squeeze con peso",
  "weighted straight bar dip": "Recto bar fondo con peso",
  "weighted stretch lunge": "Estiramiento zancada con peso",
  "weighted svend press": "Svend press con peso",
  "weighted three bench dips": "Three bench fondos con peso",
  "weighted tricep dips": "Tríceps fondos con peso",
  "weighted triceps dip on high parallel bars": "Tríceps fondo alta parallel bars con peso",
  "wheel rollerout": "Rollerout con rueda",
  "wheel run": "Run con rueda",
  "wide grip pull-up": "Agarre amplio dominada",
  "wide grip rear pull-up": "Agarre amplio rear dominada",
  "wide hand push up": "Amplio hand empuje up",
  "wide-grip chest dip on high parallel bars": "Agarre amplio pecho fondo alta parallel bars",
  "wind sprints": "Wind sprints",
  "world greatest stretch": "World greatest estiramiento",
  "wrist circles": "Muñeca circles",
  "wrist rollerer": "Muñeca rollerer",
}
