const EQUIPMENT_MAP: Record<string, string> = {
  'body weight': 'peso corporal',
  dumbbell: 'mancuernas',
  cable: 'polea',
  barbell: 'barra',
  'leverage machine': 'máquina',
  band: 'banda elástica',
  'smith machine': 'máquina Smith',
  kettlebell: 'kettlebell',
  weighted: 'con peso',
  'stability ball': 'balón suizo',
  'ez barbell': 'barra EZ',
  'medicine ball': 'balón medicinal',
  rope: 'soga',
  machine: 'máquina',
  other: 'otro',
}

const MUSCLE_MAP: Record<string, string> = {
  abs: 'abdominales',
  abdominals: 'abdominales',
  'rectus abdominis': 'recto abdominal',
  obliques: 'oblicuos',
  biceps: 'bíceps',
  'biceps brachii': 'bíceps braquial',
  triceps: 'tríceps',
  'triceps brachii': 'tríceps braquial',
  shoulders: 'hombros',
  delts: 'deltoides',
  deltoids: 'deltoides',
  deltoid: 'deltoides',
  'anterior deltoid': 'deltoides anterior',
  'lateral deltoid': 'deltoides lateral',
  'medial deltoid': 'deltoides medio',
  'posterior deltoid': 'deltoides posterior',
  chest: 'pecho',
  pecs: 'pectorales',
  pectorals: 'pectorales',
  'pectoralis major': 'pectoral mayor',
  'pectoralis minor': 'pectoral menor',
  back: 'espalda',
  lats: 'dorsales',
  'latissimus dorsi': 'dorsal ancho',
  traps: 'trapecios',
  trapezius: 'trapecios',
  rhomboids: 'romboides',
  'erector spinae': 'erectores espinales',
  serratus: 'serrato',
  'lower back': 'lumbar',
  'hip flexors': 'flexores de cadera',
  forearms: 'antebrazos',
  brachialis: 'braquial',
  calves: 'pantorrillas',
  gastrocnemius: 'gastrocnemio',
  soleus: 'sóleo',
  'tibialis anterior': 'tibial anterior',
  quads: 'cuádriceps',
  quadriceps: 'cuádriceps',
  hamstrings: 'isquiotibiales',
  glutes: 'glúteos',
  gluteals: 'glúteos',
  'gluteus maximus': 'glúteo mayor',
  hips: 'caderas',
  adductors: 'aductores',
  abductors: 'abductores',
  neck: 'cuello',
  'levator scapulae': 'elevador de escápula',
  core: 'core',
  infraspinatus: 'infraespinoso',
  supraspinatus: 'supraespinoso',
  'teres major': 'redondo mayor',
  'teres minor': 'redondo menor',
  wrist: 'muñeca',
  ankle: 'tobillo',
}

const NAME_WORD_MAP: Record<string, string> = {
  barbell: 'barra',
  dumbbell: 'mancuerna',
  dumbbells: 'mancuernas',
  cable: 'polea',
  'body weight': 'peso corporal',
  'pull-up': 'dominada',
  'pull-ups': 'dominadas',
  pullup: 'dominada',
  'push-up': 'flexión',
  'push-ups': 'flexiones',
  pushup: 'flexión',
  'sit-up': 'abdominal',
  'sit-ups': 'abdominales',
  crunch: 'crunch',
  crunchs: 'crunches',
  plank: 'plancha',
  squat: 'sentadilla',
  squats: 'sentadillas',
  deadlift: 'peso muerto',
  'bench press': 'press banca',
  press: 'press',
  row: 'remo',
  curl: 'curl',
  curls: 'curls',
  raise: 'elevación',
  raises: 'elevaciones',
  fly: 'apertura',
  flies: 'aperturas',
  lunge: 'zancada',
  lunges: 'zancadas',
  extension: 'extensión',
  kickback: 'patada',
  kickbacks: 'patadas',
  leg: 'pierna',
  legs: 'piernas',
  arm: 'brazo',
  arms: 'brazos',
  chest: 'pecho',
  back: 'espalda',
  shoulder: 'hombro',
  shoulders: 'hombros',
  hip: 'cadera',
  hips: 'caderas',
  calf: 'pantorrilla',
  calves: 'pantorrillas',
  biceps: 'bíceps',
  triceps: 'tríceps',
  hamstring: 'isquiotibial',
  hamstrings: 'isquiotibiales',
  glute: 'glúteo',
  glutes: 'glúteos',
  lat: 'dorsal',
  lats: 'dorsales',
  trap: 'trapecio',
  traps: 'trapecios',
  delt: 'deltoides',
  delts: 'deltoides',
  abs: 'abdominales',
  ab: 'abdominal',
  overhead: 'sobre la cabeza',
  seated: 'sentado',
  standing: 'de pie',
  incline: 'inclinado',
  decline: 'declinado',
  lying: 'acostado',
  front: 'frontal',
  lateral: 'lateral',
  reverse: 'inverso',
  alternating: 'alternado',
  alternate: 'alternado',
  'single-arm': 'un brazo',
  'one-arm': 'un brazo',
  machine: 'máquina',
  smith: 'Smith',
  kettlebell: 'kettlebell',
  band: 'banda',
  rope: 'soga',
  assisted: 'asistido',
  weighted: 'con peso',
  'stability ball': 'balón suizo',
  'ez barbell': 'barra EZ',
  landmine: 'landmine',
  twist: 'giro',
  'hip thrust': 'empuje de cadera',
  bridge: 'puente',
  hold: 'aguante',
  neck: 'cuello',
  wrist: 'muñeca',
  forearm: 'antebrazo',
  ankle: 'tobillo',
  toe: 'dedo',
  heel: 'talón',
  bench: 'banca',
  bar: 'barra',
  ball: 'balón',
  wheel: 'rueda',
  roller: 'rodillo',
  step: 'paso',
  skip: 'salto',
  jump: 'salto',
  jog: 'trote',
  walk: 'caminata',
  run: 'carrera',
  'run in place': 'correr en el sitio',
  stretch: 'estiramiento',
  thrust: 'empuje',
}

export function translateName(name: string): string {
  if (!name) return name
  let t = name
  for (const [en, es] of Object.entries(NAME_WORD_MAP)) {
    t = t.split(en).join(es)
  }
  return t
}

export function translateMuscle(m: string): string {
  if (!m) return m
  const key = m.trim().toLowerCase()
  return MUSCLE_MAP[key] || MUSCLE_MAP[key.replace(/s$/, '')] || m
}

export function translateEquipment(eq: string): string {
  if (!eq) return eq
  return EQUIPMENT_MAP[eq.trim().toLowerCase()] || eq
}
